// DERIVED FILE - written by `make citations` from research/citations/settlements.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Each domain is further divided into provinces, overseen by a Provincial Governor, who lives in the provincial city, which is usually central to the province.」; 「Each province is divided into counties, administered by a County Magistrate, who lives in the town which is usually central to the county.」; 「Each county is divided into Village Districts, overseen by a peasant Village Headsman who lives in the main village.」; 「Each village district usually has a number of small outlying farming communities known as hamlets.」 (the tiers the maps draw are the setting's own administrative levels, each named for the officer who lives in it.)",
 "fn-2": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「- Most hamlets have a population of 50-100 (i.e. 10-20 households)」",
 "fn-3": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「a small cluster of farms which belongs to a village district and is overseen by a village headsman who lives in the main village and not in the hamlet」 (the headman a hamlet answers to lives in the village at the head of its district, not in the hamlet.)",
 "fn-4": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「- Most villages have a population of 200-500 (i.e. 40-100 households)」",
 "fn-5": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Each province is divided into counties, administered by a County Magistrate, who lives in the town which is usually central to the county.」; 「| large towns | ~36 | ~1190 | ~42,800 | ~17% |」 (the town line of the domain's own population table.)",
 "fn-6": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Each domain is further divided into provinces, overseen by a Provincial Governor, who lives in the provincial city, which is usually central to the province.」; 「| provincial cities | ~6 | 2000 - 4000 | ~18,000 | ~7% |」 (the provincial-city line of the same table.)",
 "fn-7": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「| the capital | 1 | ~12,400 | ~12,400 | ~5% |」 (the capital line of the same table; the 12,360 the maps state is the figure the setting's own budget notes give the tier, the settled ~12,000 plus the samurai families who relocate to the capital.)",
 "fn-8": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「The median household size is generally assumed to be 5, split over 2-3 generations.」",
 "fn-9": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Remember that the county town is the \"lowest\" level of organized society that still has samurai - villages and hamlets are peasant-only!」",
 "fn-10": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「At most a samurai family might maintain a country estate close to some farmland, but the estate would never be considered to be part of the village/hamlet and most certainly would not be under the authority of any peasant village headsman.」 (a samurai's country seat stands outside the settlement, which is why the estates are drawn beyond the wall.)",
 "fn-11": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「The median household size is generally assumed to be 5, split over 2-3 generations.」",
 "fn-12": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Even the median town is ~65% farmers, since town population is counted as the in-and-around population including peasants on the immediately-surrounding fields.」 (what a town's stated figure counts: the farmers of its own fields, most of whom the sheet does not draw.)",
 "fn-13": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「| large towns | ~36 | ~1190 | ~42,800 | ~17% |」; 「| small villages | ~216 | 200 - 500 | ~75,000 | ~30% |」; 「| tiny hamlets | ~1296 | 50 - 100 | ~97,000 | ~40% |」; 「These tiers are the named settlements and sum to about ~246,000 (~98% of the domain).」 (towns, villages and hamlets are separate lines of the domain's population table and sum to the domain, so a town's figure cannot also be taking in the villages of its county.)",
 "fn-14": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Although there are a few exceptions, place names in Rokugan typically follow the same pattern across levels:」; 「- a village and its district」",
 "fn-15": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「Each village district usually has a number of small outlying farming communities known as hamlets.」; 「a small cluster of farms which belongs to a village district and is overseen by a village headsman who lives in the main village and not in the hamlet」",
 "fn-16": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「This is not usually the case with real human societies, e.g. the capital of the United States of America is not \"America City\" and the capital of Virginia is not \"Virginia City\".  However, having to remember lots of extra names is impractical, so in Rokugan these names are kept the same」 (the shared name is a departure from real naming, taken deliberately and for the reader's convenience.)",
 "fn-17": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「The Shinsei further recommended that each clan cultivates two major Fortunes to be their patrons, ensuring that every city within the clan has a temple to each of their two patron Fortunes.」; 「In the late 3rd century, Hantei the Tenth formalized the system of the Six Ministries, and along with it codified the requirement that each of the Empire's cities contains a temple to each of its clan's patron fortunes.」 (which two Fortunes hold the great temples of a settlement follows from which clan holds it.)",
 "fn-18": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「The Six Ministries exist at the Imperial level, the Clan level, the Family level, the House level, and at the provincial level (each House is divided into provinces, and the provincial government is divided into the Six Ministries as well).」; 「| 8 | Governor |」; 「| 7 | Provincial Minister |」; 「| 6 | Deputy Provincial Minister |」 (the governor, a minister for each of the six ministries, and a deputy under each of them - the households the samurai share of a provincial city is mostly made of.)",
 "fn-19": "<a href=\"SOURCES.html#l7r-median-domain\"><code>l7r-median-domain</code></a> - 「plus a small Imperial yoriki sub-station (typically ~5 yoriki each) in every one of the domain's provincial cities, auditing the tariff collection there.  These yoriki are almost all from other clans, since a daimyo's own people cannot be trusted to audit the daimyo」"
};
