// DERIVED FILE - written by `make citations` from research/citations/ways.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "no publicly readable source (searched 2026-09-12: the NRCS technical supplement \"Abutment Design for Small Bridges\" and the Wisconsin bridge manual's abutment chapter, both PDFs that would not open to a reader of text, and the Colorado bridge design manual's structure section, which is gone from the address it is listed at; searches for a timber bridge's abutment bearing length and for a scour setback in small-bridge design guidance returned nothing carrying either figure)",
 "fn-2": "<a href=\"https://solar.lowtechmagazine.com/2011/12/the-chinese-wheelbarrow/\"><code>lowtech-chinese-wheelbarrow</code></a> - 「The splendid roads are gone, and in their place, we find only narrow paths, scarcely wide enough for foot passengers and wheelbarrows.」; 「Rough unpaved cart-tracks predominated only in the Eastern plains.」 (the article credits the first observation to Rudolf Hommel's 1937 fieldwork and the second to Joseph Needham)",
 "fn-3": "<a href=\"https://solar.lowtechmagazine.com/2011/12/the-chinese-wheelbarrow/\"><code>lowtech-chinese-wheelbarrow</code></a> - 「shot through with millions of miles of well-paved paths, suitable chiefly for pedestrians, porters with carrying poles, pushers of wheelbarrows, and men carrying litters」",
 "fn-4": "no publicly readable source (searched 2026-09-12: the sentence names none, and the source pass traced no page carrying the mountains, the horses, the cart prohibitions or the guilds together or singly)",
 "fn-5": "<a href=\"https://ja.wikipedia.org/wiki/大八車\"><code>daihachiguruma-jawiki</code></a> - 「The use of the daihachiguruma was restricted by the shogunate, and was limited to Edo, Owari (Nagoya) and Sunpu (Shizuoka).」 (translated from the Japanese by this project; original: 「大八車の使用は幕府により制限され、江戸、尾張（名古屋）、駿府（静岡）に限られていた」); and on how late the highways opened to such carts, 「It was not until the Meiji period that the passage of daihachiguruma and the like was permitted on the Tokaido.」 (translated from the Japanese by this project; original: 「東海道で大八車などの通行が認可されたのは明治時代になってからのことである」)",
 "fn-6": "<a href=\"https://en.wikipedia.org/wiki/Stone_routes\"><code>stone-routes-enwiki</code></a> - 「A stone route was typically 2.7 meters (9 shaku) wide, with the two rows of stones of 30 cm x 60 cm × 25 cm size on both sides and a 90 cm (3 shaku) wide center for the bulls to walk.」",
 "fn-7": "no publicly readable source (searched 2026-09-12: a Japanese ministry history of the trunk roads is the pointer the record carried, but no page was read that gives the 9 m highway, the 4 to 7 m mountain narrowing or the 2 ken at the Hakone barrier)",
 "fn-8": "no publicly readable source (searched 2026-09-12: the sentence names none, and the source pass traced no page setting Chinese stone-slab causeways against Japanese highway paving)",
 "fn-9": "<a href=\"https://kotobank.jp/word/板橋\"><code>itabashi-kotobank</code></a> - 「a bridge made of boards」 (translated from the Japanese by this project; original: 「板で作ってある橋」)",
 "fn-10": "<a href=\"https://ja.wikipedia.org/wiki/土橋\"><code>dobashi-jawiki</code></a> - 「When logs are laid side by side with no gaps to make the bridge surface, the surface is uneven. As it is, it is hard to walk on, so earth is thrown over it and trodden down, and the earth fills the hollows and the surface becomes level.」 (translated from the Japanese by this project; original: 「丸太を隙間なく並べて橋面を作った場合、橋面が凹凸になる。そのままでは歩きにくいので、そこに土をかけて踏み固めると、へこんだ部分に土が詰まって平らになる。」)",
 "fn-11": "no publicly readable source (searched 2026-09-12: the sentence names none, and the source pass traced no page carrying the tribute rice moving by canal and river boat or the Grand Canal's place in it)"
};
