"""The canonical counts for a map, in a block a `.notes.md` carries and a test keeps honest.

WHY THIS EXISTS. Three times running, a settlement-review caught a notes paragraph asserting counts
that the shipping roll contradicted - twice in the very paragraph written to correct the previous
stale one (2026-08-29, feature 152: Inashiro's belt read 113/49 against a recorded 145/79, Sawada's
137/42 against 170/61, Kashikawa's board position and reach a roll out of date). The numbers are typed
by hand from a measurement taken before the last re-roll, and nothing notices.

So the counts a notes file states are DERIVED, not typed: `make notes-census` writes them into a
marked block, and `tests/test_notes_census.py` fails when a block disagrees with its manifest. Prose
around the block stays the author's; only the block is generated. A notes file with no block is not
required to grow one - the guard binds what is claimed, not what is omitted."""

from __future__ import annotations

import json
import math
import os
import sys
from collections import Counter
from typing import Any

BEGIN = "<!-- census: generated by `make notes-census` - do not hand-edit -->"
END = "<!-- /census -->"


def census(M: dict[str, Any]) -> str:
    """The block body for one manifest, without its markers."""
    groves = M.get("village_groves") or []
    wb = [g for g in groves if g.get("role") == "windbreak"]
    cp = [g for g in groves if g.get("role") != "windbreak"]
    houses = [(float(h["x"]), float(h["y"])) for h in (M.get("houses") or [])]
    fx = Counter(str(x.get("form") or x.get("kind")) for x in (M.get("farm_fixtures") or []))
    rows = [
        f"- windbreak: **{sum(len(g['clumps']) for g in wb)}** clumps drawn, **{sum(len(g.get('clumps_offpage') or []) for g in wb)}** off the page",
        f"- copse: **{sum(len(g['clumps']) for g in cp)}** clumps drawn",
        f"- farmhouses: **{len(houses)}**",
        f"- farmstead fixtures: {', '.join(f'{k} **{v}**' for k, v in sorted(fx.items())) or 'none'}",
    ]
    boards = [b for b in (M.get("kosatsuba") or []) if isinstance(b, dict)]
    for b in boards:
        near = sum(1 for h in houses if math.dist(h, (float(b["x"]), float(b["y"]))) <= 250.0)
        rows.append(f"- notice board at **({float(b['x']):.1f}, {float(b['y']):.1f})**, **{near}** of {len(houses)} farmhouses within 250 ft")
    return "\n".join(rows)


def block(M: dict[str, Any]) -> str:
    return f"{BEGIN}\n{census(M)}\n{END}"


def replace(text: str, M: dict[str, Any]) -> str:
    """The notes text with its census block refreshed, or unchanged when it carries none."""
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < i:
        return text
    return text[:i] + block(M) + text[j + len(END) :]


def main(argv: list[str]) -> int:
    if not argv:
        print("usage: notes_census.py <manifest.json> [...]  - rewrites each map's <name>.notes.md block", file=sys.stderr)
        return 2
    touched = 0
    for path in argv:
        with open(path, encoding="utf-8") as fh:
            M = json.load(fh)
        notes = os.path.splitext(path)[0] + ".notes.md"
        if not os.path.exists(notes):
            print(f"  {os.path.basename(notes)}: no notes file")
            continue
        with open(notes, encoding="utf-8") as fh:
            text = fh.read()
        out = replace(text, M)
        if out == text:
            print(f"  {os.path.basename(notes)}: {'no census block' if BEGIN not in text else 'already current'}")
            continue
        with open(notes, "w", encoding="utf-8") as fh:
            fh.write(out)
        touched += 1
        print(f"  {os.path.basename(notes)}: census refreshed")
    print(f"notes-census: {touched} file(s) rewritten")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
