#!/usr/bin/env python3
"""Automated tests for Mode B settlement maps (diagram skill).

Obtains every SCRIPTED map in pool/ through the gate cache (feature 026: a
verified gen-cache hit skips GENERATION only; any doubt - or GATE_NO_CACHE=1 -
regenerates) and runs the full check_village gate over the resulting manifest.
This pins the whole Mode B process: any change to the settlement/ package, a
scripted engine, or a spec that breaks an invariant (no overlaps, every field
ringed, households-consistent house counts, channels anchored, no label
overlaps, ...) fails here - checking is never cached.

THE HAND-AUTHORED POOL IS FROZEN (GM 2026-08-16; migration-plan.md "The accepted
trade"): legacy maps are permanent exhibits - never regenerated, never re-gated -
so this sweep covers scripted maps only, and engine changes are free to alter
behavior without holding 19 deprecated compositions byte-identical. poolmaps.py
is the classification; the ratchet below keeps every pool gen accounted for.

Works under pytest OR standalone:
    python3 -m pytest test_villages.py -q     # from the diagram skill directory
    python3 test_villages.py                  # no pytest required
"""

import json
import os
import sys

import pytest

from l7r.diagram.overlap import point_in_poly
from l7r.diagram.pipeline import gencache, poolmaps

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # the skill root; the tests live one level down in tests/
POOL = os.path.join(HERE, poolmaps.LIVE_TREE)
LEGACY_POOL = os.path.join(HERE, poolmaps.LEGACY_TREE)


# THE SWEEP IS LIVE + SCRIPTED. The tree is now STATED rather than implied by a glob: a frozen map
# is never regenerated and a compound has no manifest to gate (feature 161).
GENERATORS = poolmaps.gens(trees=(poolmaps.LIVE_TREE,), kinds={"scripted"}, skill_dir=HERE)


def test_every_pool_gen_is_classified():
    """THE RATCHET for poolmaps.classify: every `.gen.py` in the pool is a swept scripted map, a
    declared Mode A compound, or a declared FROZEN legacy map - anything else is a map nobody
    checks. The scripted detection is SOURCE TEXT (which engine the gen imports), so a gen built on
    a NEW engine module is invisible to it - the "a check that never runs looks exactly like a
    check that passes" failure applied to a whole map. It happened on 2026-08-11: the scripted demo
    maps (then in `pool/experiments/`, since dissolved into `pool/hamlets/`) import `hamletgen`
    rather than `settlement`, so four maps sat in the pool being regenerated by nobody and gated by
    nothing, with the sweep entirely green. Both declared lists are also checked AGAINST the pool,
    so a rename or deletion cannot leave a stale name behind."""
    # BOTH TREES (feature 161, FR-013a). The ratchet is the guard that every map in the repository
    # is accounted for, so narrowing it to the live pool would silently drop 18 of the 23 Mode B
    # maps from its coverage - and the stale-name assertion below resolves LEGACY_FROZEN_GENS
    # against the legacy tree, so it would also turn red. Distinct from GENERATORS above, which is
    # the live-only regeneration sweep.
    bundles = poolmaps.bundles(skill_dir=HERE)
    gens = [b.gen for b in bundles]
    unknown = sorted(os.path.basename(g) for g in gens if poolmaps.classify(g) == "unknown")
    assert not unknown, (
        f"pool gen(s) that are neither scripted, compound, nor frozen legacy: {unknown} - a map in "
        f"the pool that no test regenerates is a map with no gate. If it is built on a new scripted "
        f"engine module, add that module to poolmaps.SCRIPTED_ENGINES; if it is a Mode A compound "
        f"plan, add it to poolmaps.COMPOUND_GENS. Hand-authoring a new Mode B map is DEPRECATED "
        f"(migration-plan.md) and the frozen legacy list is closed - extending it takes a GM decision."
    )
    present = {os.path.basename(g) for g in gens}
    stale = sorted((poolmaps.LEGACY_FROZEN_GENS | poolmaps.COMPOUND_GENS) - present)
    assert not stale, f"declared in poolmaps.py but not present in the pool (renamed or deleted?): {stale}"
    # AND EACH MAP IS IN THE RIGHT TREE (feature 161). A frozen exhibit sitting in the live pool
    # would be regenerated by the sweep and overwrite an artifact nobody can rebuild; a scripted map
    # in the frozen tree would never be rolled or gated again. Both are silent without this.
    misfiled = [f"{b.stem} is in {b.tree} but classifies {b.kind}" for b in bundles if (b.kind == "legacy") != (b.tree == poolmaps.LEGACY_TREE)]
    assert not misfiled, (
        "a map is in the wrong pool tree: " + "; ".join(misfiled) + " - `pool/` holds what is LIVE "
        "(scripted + Mode A compound), `legacy-hand-authored-pool/` the FROZEN hand-authored "
        "exhibits. When a map is CONVERTED to scripted generation it moves trees (git mv into pool/)."
    )


def test_poolmaps_classifies_each_kind(tmp_path):
    assert poolmaps.classify(os.path.join(POOL, "hamlets", "sawada", "sawada.gen.py")) == "scripted"
    assert poolmaps.classify(os.path.join(LEGACY_POOL, "hamlets", "moritono", "moritono.gen.py")) == "legacy"
    assert poolmaps.classify(os.path.join(POOL, "magistracies", "county-magistracy-example", "county-magistracy-example.gen.py")) == "compound"
    stray = tmp_path / "stray.gen.py"
    stray.write_text("print('no engine import at all')\n")
    assert poolmaps.classify(str(stray)) == "unknown"


# HOW LONG A GEN IS ALLOWED TO TAKE (CPU seconds). WHY (GM 2026-08-03, right after the incident
# that motivates it): Minami's gen silently became a 45+ MINUTE grind when the paddy-well rule
# landed - `_well_ground_clear` re-scanned all 927 drawn basins and ~580 watercourse segments per
# candidate seat - and nothing failed; sessions just waited it out, or timed out and misdiagnosed
# it (see CLAUDE.md "Gate and sweep timings"). A budget turns "mysteriously slow" into a loud,
# early, NAMED failure. It is aimed at that pathological class - a per-candidate scan of static
# geometry, which this engine keeps regrowing - not at 20% drift, so another session adding a
# legitimate rule should never have to argue with it.
#
# CALIBRATE AGAINST THE GATE, NOT A SOLO RUN. These asserts fire inside `make done`, i.e. under
# `pytest -n auto` (22 workers here), where a gen's own CPU TIME inflates 2-4x through cache and
# memory-bandwidth contention - process CPU time is immune to WAITING for a core, not to needing
# more cycles for the same work. Budgets tuned on solo timings duly went off on their first gate
# run (kikuta: 10.9s solo, 36.2s under the gate, against a 30s budget). So each entry is ~4x its
# SOLO measurement, i.e. roughly 1.5x its worst observed under-gate time. A map that legitimately
# outgrows its entry gets a bigger one WITH the reason recorded, the same discipline as a waiver.
GEN_TIME_BUDGET_S = 45.0  # default: an ordinary map measures 1-7s solo, comfortably under even inflated
GEN_TIME_BUDGETS = {
    # (The heavy hand-authored maps - minami at 60s, nagahara/tango/kikuta/hoshizora at 50s - had
    # entries here until the 2026-08-16 legacy freeze took them out of the sweep entirely.)
    # THE SCRIPTED HAMLETS (2026-08-12) are slow for a reason that is not the pathological shape this
    # guard exists for, and the reason is inherent rather than a regression: `hamletgen.fit_field`
    # BISECTS a size multiplier against the drawn plot area, carving the whole comb several times per
    # map to land the paddy acreage the household count implies - so one map is several maps' worth of
    # carve. Passing `build_comb` its principled `grain` of 2.0 (see waterfields.py) added a further
    # ~35% on top, measured on Sawada: 14.6s solo at 1.0, 19.8s at 2.0, from the wider ditches and the
    # extra footbridge arithmetic they need. Entries are ~4x the solo measurement, as above.
    #
    # RECALIBRATED 2026-08-19 against MEASURED solo times, because the entries had drifted into
    # flakiness rather than protection. The policy above ("~4x the solo measurement") is unchanged;
    # only the solo figures it multiplies were stale.
    #
    # HONEST ABOUT THE SHARE THAT IS THIS SESSION'S: a first pass claimed the clone and a detached
    # worktree at main's tip measured "the same", on whole-gen timings that were too coarse to see it.
    # A per-STAGE profile of the real pool specs says otherwise - build-stage totals, mine vs main:
    # kashikawa 29.6s vs 21.8s (+36%), inashiro 20.7s vs 17.9s (+16%), sawada 61.7s vs 57.2s (+8%).
    # That is the real cost of the rotated-bbox woodland test, its shrink ladder and the cluster band
    # work, and it is NOT pathological: no single stage explodes on any corpus map, and `stage_web` is
    # actually faster on kashikawa (1.95s vs 2.16s). But it is not zero either, so the budgets below
    # absorb a genuine increase as well as the older drift, and a reader should know which is which.
    #
    #     kashikawa 32.2s (comment said ~16)   sawada 30.6s (said ~20)
    #     inashiro  22.4s (said ~11)           mizuguchi 18.9s (had no entry at all)
    #
    # Solo times roughly DOUBLED since the entries were written on 2026-08-12, so 4x-of-old had become
    # ~2x-of-current - and the assertion does not run solo. It runs inside `pytest -n auto`, where CPU
    # per gen inflates about 2.5x from cache and hyperthread contention: measured in-gate 57.4s against
    # 22.4s solo for inashiro, 83.1s against 32.2s for kashikawa. A budget below that multiple fails on
    # a busy box and passes on an idle one, which is a coin toss wearing a guard's clothes. It cost
    # three false gate failures in one session, each read at first as a possible perf regression.
    #
    # THE FAILURE THIS GUARD IS FOR is a pathological gen (the 2026-08-02 Minami bug: re-scanning
    # static geometry per candidate seat, 45 minutes, nothing flagged). 4x of a true solo time still
    # catches that easily; 2x of a stale one merely catches whatever else the machine was doing.
    #
    # WORTH A LOOK BUT NOT CHASED HERE: why solo doubled in a week. It tracks the features that landed
    # (the lane web, byres, the woodland scan, cluster shape), so it is probably real work rather than
    # waste - but nobody has measured which stage owns the growth, and `tools/timings.py` would answer
    # it.
    #
    # CORRECTED 2026-08-28 (feature 138; the GM: *"bisecting a field several times per map does not seem
    # like it would add up to one hundred CPU seconds"* - it does not). A per-stage profile of the seed-19
    # POLDER (110 s solo) put 57 s in `stage_web` and 22 s in `stage_track`, and the "inherent" field
    # bisection at under a second: the lane router called `clear_runs` once PER LATTICE CELL (165,611
    # calls; 36 million `seg_dist`) and the connector compared every pair of water crossings (170 million
    # `hypot`). That was exactly the pathological shape this guard exists for, hiding under a budget that
    # had been raised to fit it. On a COMB hamlet the bisection IS real - `fit_field` runs `build_comb` 7
    # times, 16-22 s on a 10-household cohort seed - but it is not what made the polder slow, and its
    # solver is left alone because changing it moves the maps. After the fabric index and the crossing
    # sweep (`hamletgen/clearance.py`, `_geom/water_index.py`): the polder 110 -> ~30 s, the reference
    # 37 -> ~21 s, every manifest byte-identical. The entries below still stand at ~4x SOLO, re-measured.
    # KUWABATA HAS AN ENTRY BECAUSE IT IS A DIKE-POND MAP, NOT BECAUSE IT IS SLOW (feature 155). It landed
    # with feature 150 and inherited the 45 s default, which the comment above says is for "an ordinary map
    # [that] measures 1-7s solo" - a mulberry-dike fishpond is not that map. Measured 2026-08-29 on this
    # clone: 26.3 s solo (the child-recorded `gen_cpu_s`), against 16.8 for inashiro and 12.9 for mizuguchi.
    # In-gate it reported 49.4 s under `-n auto` and passed serially, which is the 2.5x contention inflation
    # this block already documents - so the failure was the budget being the wrong one for the archetype,
    # not a perf regression. The entry is 4x the solo measurement, the same policy as every line below.
    # NOT a licence: if this number has to rise again, the question is what got slower, and the answer
    # belongs here beside it.
    "kuwabata": 105.0,  # 26.3s solo measured 2026-08-29
    "sawada": 125.0,  # 30.6s solo measured 2026-08-19
    "kashikawa": 130.0,  # 32.2s solo
    "inashiro": 90.0,  # 22.4s solo
    "mizuguchi": 76.0,  # 18.9s solo - had NO entry, so it fell to the shared default and was one busy box away from the same false failure
}


def _regen_and_gate(gen):
    """Obtain a map through the gate cache, then run its gate; True if every check passes.

    A verified HIT (feature 026) skips GENERATION only: the entry's stored coverage replays into
    this run, and the check battery below still judges whatever manifest was served. A miss
    regenerates in gencache's coverage-recording subprocess (with DIAGRAM_SKIP_RENDER inside -
    the gate reads the JSON manifest, never the PNG). The budget assert reads the CHILD-measured
    CPU, so it applies exactly when generation actually ran."""
    manifest, how, cpu_s = gencache.gate_obtain(gen)
    if how == "REGENERATED":
        assert cpu_s is not None
        name = os.path.basename(gen)[: -len(".gen.py")]
        budget = GEN_TIME_BUDGETS.get(name, GEN_TIME_BUDGET_S)
        assert cpu_s <= budget or os.environ.get("DIAGRAM_ALLOW_SLOW_GENS") == "1", (
            f"{name}.gen.py took {cpu_s:.1f}s CPU against a {budget:.0f}s budget - it is a SURPRISE that this gen "
            f"takes so long, and the last time one did (Minami, 2026-08-02) it was a 45-minute perf bug that "
            f"nothing flagged. Please consider whether a perf regression landed (the known shape: re-scanning "
            f"static geometry per candidate seat - see CLAUDE.md 'Gate and sweep timings') before anything else. "
            f"If you are CERTAIN perf is fine, rerun with DIAGRAM_ALLOW_SLOW_GENS=1, and raise this map's entry "
            f"in GEN_TIME_BUDGETS with the reason recorded beside it."
        )
    assert os.path.exists(manifest), f"{os.path.basename(gen)} produced no manifest"
    # THE SWEEP NO LONGER GATES (feature 166). It used to end by running the whole check battery on
    # the manifest it had just produced, which is the architecture this feature retired: a generator
    # is proven by its placers' own tests, not audited afresh on every map it draws. What the sweep
    # still proves - and the only thing it ever proved that the battery did not - is that every
    # shipped generator RUNS, inside its time budget, and emits a manifest.
    return True


def test_at_least_one_village_exists():
    assert GENERATORS, "no *.gen.py village generators found in pool/"


def test_slow_gen_budget_fires_and_the_override_silences_it(tmp_path, monkeypatch):
    # the guard must be SHOWN to fire (a check that never fires looks exactly like a check that
    # passes): a CPU-burning fake gen against a near-zero budget trips the surprise message, and
    # the documented override lets it through (to then fail on the missing manifest instead,
    # proving the budget assert itself was silenced)
    gen = tmp_path / "snail.gen.py"
    monkeypatch.setitem(GEN_TIME_BUDGETS, "snail", 0.001)
    # THE OBTAIN IS STUBBED (feature 135, third pass): this used to spawn two real `coverage run` subprocesses
    # on a 50 ms fake gen - 2.6 s, the gate's second-longest test - to prove an assert that reads only the
    # CPU figure `gate_obtain` returns. The figure's measurement is `gate_obtain`'s own contract, proven in
    # tests/gate/pipeline/test_gencache.py (`gen_cpu_s >= 0` on a miss); this test proves the BUDGET fires
    # on that figure and that the documented override silences it, which a stub shows in milliseconds.
    monkeypatch.setattr(gencache, "gate_obtain", lambda g: (str(tmp_path / "snail.json"), "REGENERATED", 0.05))
    # OWN THE ENVIRONMENT, do not inherit it (2026-08-03): the override is documented for
    # WHOLE-SWEEP use ("rerun with DIAGRAM_ALLOW_SLOW_GENS=1"), and a session that follows that
    # advice silenced the budget for this test too - so the one test proving the guard still has
    # teeth failed precisely when someone used the guard as designed, turning the escape hatch into
    # a guaranteed red gate. The fire-half must be measured with the override OFF regardless of how
    # the sweep was invoked.
    monkeypatch.delenv("DIAGRAM_ALLOW_SLOW_GENS", raising=False)
    with pytest.raises(AssertionError, match="SURPRISE"):
        _regen_and_gate(str(gen))
    monkeypatch.setenv("DIAGRAM_ALLOW_SLOW_GENS", "1")
    with pytest.raises(AssertionError, match="produced no manifest"):
        _regen_and_gate(str(gen))


def _channels_under_plots(svgpath):
    """SVG-level z-order audit: every field channel (the #6C9CBE supply / #7C9EB0 drain strokes)
    must draw OVER the paddy plots it crosses. A channel whose midpoint lies inside a plot polygon
    that appears LATER in the document is painted over - the invisible-ditch-net defect (GM
    2026-07-21: Hoshizora's canals "rendering below the rice paddies"; also Hikari-no-sato's
    first comb under its second comb's plots, and the cities' residual 2nd-fan hole). This is
    deliberately an SVG test, not a manifest check: scatter/paint order is not manifest-recorded,
    same as the per-tuft skips. Returns the covered channels as (x, y) midpoints."""
    import re

    with open(svgpath) as fh:
        svg = fh.read()
    plots = []
    for m in re.finditer(r'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{6}" stroke="#[0-9A-Fa-f]{6}" stroke-width="2"', svg):
        plots.append((m.start(), [tuple(map(float, p.split(","))) for p in m.group(1).split()]))
    covered = []
    for m in re.finditer(r'<path d="M([^"]+)" fill="none" stroke="#(?:6C9CBE|7C9EB0)"', svg):
        coords = [tuple(map(float, p.split(","))) for p in m.group(1).replace(" L", ";").split(";")]
        mid = coords[len(coords) // 2]
        if any(pos > m.start() and point_in_poly(mid[0], mid[1], pts) for pos, pts in plots):
            covered.append((round(mid[0]), round(mid[1])))
    return covered


def _typical_cell_acres(svgpath, ftpx):
    """Real-feet area of the TYPICAL leveled paddy cell (a bund-stroked plot polygon), taking the mean
    of the 45th-75th percentile band (the regular interior cells, above the edge wedges). Pins the
    ~0.05-acre paddy calibration (GM 2026-07-22, see settlements.md 'Paddy cell size'). SVG-measured,
    not a manifest gate, because villages do not record plot_polys - same tier as the ditch z-order audit."""
    import re
    import statistics

    with open(svgpath) as fh:
        svg = fh.read()

    def _sl(poly):
        return abs(sum(poly[i][0] * poly[(i + 1) % len(poly)][1] - poly[(i + 1) % len(poly)][0] * poly[i][1] for i in range(len(poly)))) / 2

    from l7r.diagram.waterfields import AZE

    # comb plots carry the AZE bund stroke at aze_w's 2-decimal width (the patchwork field() path
    # formats its width to 1 decimal, so \d+\.\d\d selects exactly the comb cells, as the old
    # literal stroke-width="2" did) - keyed to the AZE constant so a recolor cannot silently
    # de-match this parser again (the 2026-07-24 aze recolor broke the old hardcoded signature)
    areas = sorted(
        _sl([tuple(map(float, p.split(","))) for p in m.group(1).split()]) * ftpx * ftpx
        for m in re.finditer(rf'<polygon points="([^"]+)" fill="#[0-9A-Fa-f]{{6}}" stroke="{AZE}" stroke-width="\d+\.\d\d"', svg)
    )
    if len(areas) < 8:
        return None
    band = areas[int(len(areas) * 0.45) : int(len(areas) * 0.75)]
    return statistics.mean(band) / 43560


# one test per village (not one loop over all): a failure names its map directly, and a
# parallel runner (pytest-xdist) can spread the regens instead of serializing them in one test


def test_every_scripted_comb_fan_records_its_design_cell() -> None:
    """The size floor's declaration guard: no `cell`, no `paddy_basins_are_worth_their_bund`.

    That check measures each basin against the DESIGN CELL the placer carved to, recorded on the
    field by `build_comb`, and it SKIPS a field that has none - which is correct, because the
    terrace, ribbon and polder engines record none and are deliberately exempt from an area floor
    (hill rice is where the real micro-basins are). The cost of that design is that dropping the
    record would retire the floor on every comb map at once with the gate still green - "a check
    that never RUNS looks exactly like a check that passes".

    IT IS A TEST RATHER THAN A GATE CHECK, deliberately. An in-gate rule fires on the two dozen
    frozen hamlet manifests in pool/regressions/ that were captured before `cell` existed, for a
    reason unrelated to the defect each was frozen for - and a fixture cannot be re-captured
    without losing the geometry it exists to pin. So the guard reads the SHIPPED pool maps instead,
    where the record either exists or the floor is dark.
    """
    seen = 0
    for gen in GENERATORS:
        path = gen[: -len(".gen.py")] + ".json"
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            M = json.load(fh)
        irrigated = {c.get("field") for c in M.get("field_ditches") or []}
        if M.get("meta", {}).get("field_archetype") in ("polder_grid", "mulberry_dike_fishpond"):
            continue  # a POLDER is not a comb fan: build_polder carves no design cell and the floor is a comb rule (the check's own note: a field with no `cell` is a terrace, ribbon or polder); Kuwabata was the first scripted polder in the pool (feature 150)
        for fld in M.get("fields") or []:
            if fld.get("kind") != "paddy" or fld.get("name") not in irrigated:
                continue
            if not fld.get("plot_rings"):
                continue  # a fan that records no rings is invisible to the floor either way
            seen += 1
            assert fld.get("cell"), (
                f"{os.path.basename(gen)}: comb fan {fld.get('name')!r} records no `cell`, so "
                "paddy_basins_are_worth_their_bund silently skips it and the paddy size floor is "
                "unguarded on this map (build_comb must return `cell`; see _TOE_MIN_AREA)"
            )
    assert seen >= 4, f"the guard inspected only {seen} comb fans - it has stopped reaching the scripted pool and is no longer guarding anything"


if __name__ == "__main__":
    rc = 0
    for g in GENERATORS:
        ok = _regen_and_gate(g)
        print(("PASS " if ok else "FAIL ") + os.path.basename(g))
        rc |= 0 if ok else 1
    sys.exit(rc)


def test_every_pool_render_matches_its_own_svg_geometry():
    """A PNG that does not match its SVG's viewBox is a STALE RENDER, and it is invisible to every other
    check (settlement-review, feature 155).

    Sawada and kashikawa shipped PNGs from the roll BEFORE their lane webs were fixed - kashikawa's matched
    the pre-delta manifest at 96% - so the picture the GM opens showed a farmhouse the lane no longer crossed.
    The mechanism: the gate's regeneration child runs with `DIAGRAM_SKIP_RENDER=1` (it reads the manifest,
    never the raster), so a gate-driven roll writes a new `.json` and `.svg` and no `.png`, and the old
    raster stays on disk beside them. Nothing compared the two.

    Geometry is the cheap invariant that catches the whole class: `render_png` scales the SVG to a fixed
    width, so the height is determined by the viewBox aspect.

    **FEATURE 178 CHANGED WHAT THIS READS, AND THE HONEST ACCOUNT OF WHAT WAS LOST IS PART OF THE TEST.**
    It used to walk both pool trees and compare an on-disk `.png` against its on-disk `.svg`. In a clean
    checkout the only maps it could actually check were the FROZEN exhibits, because a live map's renders
    are gitignored - so 97.9 MB of tracked `.svg`/`.png` existed to let eight comparisons happen. The GM
    untracked every generated render (*"I don't see why we should be tracking those renders"*), so those
    files are gone from git and from history; they live at `/host-l7r-repo/diagram-render-archive/`.

    What replaces them is 1,180 bytes: `tests/fixtures/frozen_exhibit_renders.json` records each exhibit's
    PNG pixel dimensions, and the assertion checks them against a SECOND, INDEPENDENT source - the
    exhibit's own tracked `.json` manifest, whose `meta.view` is the same rectangle the SVG's viewBox
    carries. That is not a tautology: the two files are written by different code paths, and a wrong number
    in either one fails. What it can no longer catch is a raster on disk drifting from its manifest for a
    FROZEN exhibit, and the reason that is acceptable is specific rather than convenient - a frozen exhibit
    is write-once and no generator ever re-rolls it, so nothing this repository does can introduce that
    drift. The door the old check watched has stopped existing.

    A LIVE map's renders are still compared file-to-file whenever they are present, which is where the
    drift this test was built for actually happens."""
    import json
    import re
    import struct
    from pathlib import Path

    recorded = json.loads((Path(HERE) / "tests" / "fixtures" / "frozen_exhibit_renders.json").read_text())["renders"]
    assert len(recorded) == 8, "the eight frozen hamlet exhibits; a change here is a change to the archive"

    # 1. ALWAYS, needing no render on disk: the recorded raster against the manifest's own rectangle.
    for stem, rec in sorted(recorded.items()):
        man = json.loads((Path(HERE) / "legacy-hand-authored-pool" / "hamlets" / stem / f"{stem}.json").read_text())
        view = man.get("meta", {}).get("view")
        assert view and len(view) == 4, f"{stem}: no meta.view to check against - the second source is gone"
        _x, _y, vw, vh = (float(v) for v in view)
        w, h = rec["png"]
        expected = round(w * vh / vw)
        assert abs(h - expected) <= 1, (
            f"{stem}: the recorded raster is {w}x{h}, but its manifest's meta.view ({vw:.0f}x{vh:.0f}) makes a "
            f"{w}-wide render {expected} tall. One of the two is wrong - they are written by different code "
            f"paths, which is what makes this worth asserting."
        )

    # 2. WHERE THE FILES ARE PRESENT, the original file-to-file comparison, unchanged.
    for b in poolmaps.bundles(skill_dir=HERE):
        if b.tier != "hamlets" or not (os.path.isfile(b.path(".svg")) and os.path.isfile(b.path(".png"))):
            continue
        head = Path(b.path(".svg")).read_text(errors="ignore")[:4000]
        box = re.search(r'viewBox="([-\d.eE ]+)"', head)
        if not box:
            continue
        _x, _y, vw, vh = (float(v) for v in box.group(1).split())
        w, h = struct.unpack(">II", Path(b.path(".png")).read_bytes()[16:24])
        expected = round(w * vh / vw)
        assert abs(h - expected) <= 1, (
            f"{b.stem}.png is {w}x{h} but its own SVG's viewBox ({vw:.0f}x{vh:.0f}) makes a "
            f"{w}-wide render {expected} tall - the raster is from a DIFFERENT roll than the manifest beside "
            f"it. Re-render the map (`make maps SCOPE=all`); every consumer that maps world coordinates "
            f"through the viewBox onto the PNG, `tools/crop_map.py` included, is silently misplaced until you do."
        )
