// DERIVED FILE - written by `make citations` from research/citations/cities/defenses.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "<a href=\"https://zh.wikipedia.org/wiki/西安城墙\"><code>xian-wall-zhwiki</code></a> - 「On the outer face of the city wall are built 98 enemy platforms (ditai), projecting 12 meters out from the wall, 20 meters wide, level in height with the wall, each 120 meters from the next, exactly within the range of bows and firearms.」 (translated from the Chinese by this project; original: 「城墙的外壁筑98座敌台，延伸出墙12米，宽20米，高与城齐，各自相距120米，恰在弓箭和火铳的射程范围内。」)",
 "fn-2": "<a href=\"https://zh.wikipedia.org/wiki/西安城墙\"><code>xian-wall-zhwiki</code></a> - 「The city wall is 12 meters high, 15-18 meters wide at the base, and 12-14 meters wide at the top.」 (translated from the Chinese by this project; original: 「城垣高12米，底宽15-18米，顶宽12-14米。」)",
 "fn-3": "<a href=\"https://zh.wikipedia.org/wiki/西安城墙\"><code>xian-wall-zhwiki</code></a> - 「On the outer face of the city wall are built 98 enemy platforms (ditai), projecting 12 meters out from the wall, 20 meters wide, level in height with the wall」 (translated from the Chinese by this project; original: 「城墙的外壁筑98座敌台，延伸出墙12米，宽20米，高与城齐」) (98 enemy platforms on the outer face, projecting 12 m, 20 m wide, as high as the wall. (20 m x 12 m = ~66 x 39 ft, so the ~65x40 ft figure is the Xi'an one.))",
 "fn-4": "<a href=\"https://ja.wikipedia.org/wiki/%E7%AE%B1%E6%A0%B9%E9%96%A2\"><code>hakone-seki-jawiki</code></a> - 「The buildings comprised the \"men-bansho\" (upper guard office, guards' duty room, rest room, bath), the \"mukai-bansho\" (half-duty post, rest room, jail), stables, a corner watch post and a notice board, all enclosed by a fence.」 (translated from the Japanese by this project; original: 「建造物は上御番所・番士詰所・休息所・風呂場からなる「面番所」、所詰半番・休息所・牢屋からなる「向番所」、厩、辻番、高札場などが設置され、柵で囲まれていた。」)",
 "fn-5": "<a href=\"https://ja.wikipedia.org/wiki/%E7%AE%B1%E6%A0%B9%E9%96%A2\"><code>hakone-seki-jawiki</code></a> - <!-- SUMMARY-ONLY - the registry records \"that the two stations face each other across the road is SUMMARY-ONLY (search synthesis of hakonesekisyo.jp)\". Confirmed on the page: --> the ja.wikipedia article does NOT state the relative placement; the nearest passage is 「the distance between the two gates was about 18 meters, and」 (translated from the Japanese by this project; original: 「両門の間は約18メートルで」) (the source that would settle it is hakonesekisyo.jp.<!-- not in the registry with a URL -->)",
 "fn-6": "<a href=\"https://zh.wikipedia.org/wiki/%E7%93%AE%E5%9F%8E\"><code>wengcheng-zhwiki</code></a> - 「A wengcheng is a small gate-protecting walled enclosure, semicircular or square, built outside a city gate in order to strengthen the defense of a fortress or of a strategic pass」 (translated from the Chinese by this project; original: 「甕城是为了加强城堡或关隘的防守，而在城门外修建的半圆形或方形的护门小城」)",
 "fn-7": "<a href=\"https://zh.wikipedia.org/wiki/%E7%93%AE%E5%9F%8E\"><code>wengcheng-zhwiki</code></a> - 「The barbican's gate is usually not on the same straight line as the city gate it protects, so that the besieging side has to turn its siege weapons in another direction instead of driving straight in.」 (translated from the Chinese by this project; original: 「瓮城城门通常与所保护的城门不在同一直线上，使得攻城方需要將攻城武器轉往另一方向而不是長驅直入。」)",
 "fn-8": "<a href=\"https://ja.wikipedia.org/wiki/%E7%AE%B1%E6%A0%B9%E9%96%A2\"><code>hakone-seki-jawiki</code></a> - <!-- SUMMARY-ONLY - registry: \"that the two stations face each other across the road is SUMMARY-ONLY (search synthesis of hakonesekisyo.jp)\". --> The page supports only the facility list (quoted above), the two gates 18 m apart (「the distance between the two gates was about 18 meters, and」 (translated from the Japanese by this project; original: 「両門の間は約18メートルで」)) and the inspection regime 「a strict surveillance regime symbolized by \"guns coming in, women going out\" was adopted.」 (translated from the Japanese by this project; original: 「「入鉄炮に出女」に象徴される厳重な監視体制が採られた」) (The \"opposite each other across the road\" and \"passing between them\" claims are not on the page.)",
 "fn-9": "<a href=\"https://zh.wikipedia.org/wiki/鈔關\"><code>chaoguan-zhwiki</code></a> - 「A tax barrier (shuiguan) was a checkpoint set up by the government at goods collection-and-distribution places and at key water and land junctions during China's Ming and Qing dynasties, used to levy transit tax on goods, vehicles and boats passing through.」 (translated from the Chinese by this project; original: 「税关是中國明清兩代，政府在货物集散地和水陆要冲设立的关卡，用以向过境物品、车辆、船舶收取过境税。」)",
 "fn-10": "<a href=\"https://zh.wikipedia.org/wiki/鈔關\"><code>chaoguan-zhwiki</code></a> - 「A tax barrier (shuiguan) was a checkpoint set up by the government at goods collection-and-distribution places and at key water and land junctions during China's Ming and Qing dynasties」 (translated from the Chinese by this project; original: 「税关是中國明清兩代，政府在货物集散地和水陆要冲设立的关卡」); 「By the Wanli era, only the eight most important chaoguan were kept, seven of them along the Grand Canal, in order from north to south: Chongwenmen, Hexiwu, Linqing, Huai'an, Yangzhou, Xushuguan, and Beixinguan (Hangzhou); only Jiujiang in Jiangxi was an exception.」 (translated from the Chinese by this project; original: 「到万历年间，只保留了最重要的8所钞关，其中7所在运河沿线，从北向南依次是：崇文门、河西务、临清、淮安、扬州、浒墅关、北新关（杭州），只有江西九江是一个例外。」) (... checkpoints at goods-distribution centers and strategic water/land junctions; by the Wanli era only the eight most important chaoguan were kept, seven of them along the Grand Canal - from north to south Chongwenmen, Hexiwu, Linqing, Huai'an, Yangzhou, Xushuguan, Beixinguan (Hangzhou) - with Jiujiang in Jiangxi the only exception. Caveat: two of the eight are named at gates - 崇文门 (a Beijing city gate) and 「set at Yijiang Gate in Yangzhou's new city」 (translated from the Chinese by this project; original: 「设于扬州新城挹江门」) - so \"on canals, not at gates\" is true of the general practice but not of every station; none of the eight is a county seat.<!-- which is the claim the correction actually makes -->)",
 "fn-11": "<a href=\"https://ja.wikipedia.org/wiki/%E7%AE%B1%E6%A0%B9%E9%96%A2\"><code>hakone-seki-jawiki</code></a> - as above: the page does not state that the two stations face each other (the nearest passage is 「the distance between the two gates was about 18 meters, and」 (translated from the Japanese by this project; original: 「両門の間は約18メートルで」)). <!-- SUMMARY-ONLY - as above; the file already labels it. -->",
 "fn-12": "<a href=\"https://zh.wikipedia.org/wiki/西安城墙\"><code>xian-wall-zhwiki</code></a> - 「On the outer face of the city wall are built 98 enemy platforms (ditai), projecting 12 meters out from the wall, 20 meters wide, level in height with the wall, each 120 meters from the next, exactly within the range of bows and firearms.」 (translated from the Chinese by this project; original: 「城墙的外壁筑98座敌台，延伸出墙12米，宽20米，高与城齐，各自相距120米，恰在弓箭和火铳的射程范围内。」) (the 120 m and its arrow-range rationale are on the page.))",
 "fn-13": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page saying that the sortie a European curtain makes through a sally port was made from the barbican court instead)<!-- the barbican itself is wengcheng-zhwiki, fn-6; what has no page is the sortie being made from it -->",
 "fn-14": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page setting the rear gate, the small walled-up postern and the water gate against the European sally port as its nearest equivalents)",
 "fn-15": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page giving a width for the moat of a provincial seat)",
 "fn-16": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page giving the clear width of a Ming gate tunnel at Nanjing or at Xi'an, or of an Edo castle-town koraimon)",
 "fn-17": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page contrasting the European round tower with the rectangular Chinese and Japanese one, or dating the roundel at the southwest corner of Xi'an's circuit)",
 "fn-18": "no publicly readable source (searched 2026-09-12: the claim entered the record with no source named, and this page's source pass found no readable page describing the follow-the-wall street or the clear lap of ground a fortified city kept inside its rampart)"
};
