// DERIVED FILE - written by `make citations` from research/citations/cities/fabric.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "<a href=\"https://www.kyototuu.jp/Life/ProverbUnaginoNedoko.html\"><code>kyototuu-unagi</code></a> - 「Toyotomi Hideyoshi taxed houses according to the width of their frontage, under the name jiguchi-sen, so it is said that people narrowed the frontage and built deep 'eel's bed' style machiya to save on tax.」 (translated from the Japanese by this project; original: 「豊臣秀吉は、「地口銭（じぐちせん）」と称される、家の間口の広さに応じて課税をしたことで、間口は狭くして、奥行きのある「鰻の寝床」様式の町家を建てて節税をしたといわれる」) (Note the page's own hedge といわれる (\"it is said\").)<!-- the record's L21 correction already marks this as the popular explanation that `kyomachiya-jawiki` disputes. -->",
 "fn-2": "<a href=\"https://ja.wikipedia.org/wiki/%E9%95%B7%E5%B1%8B\"><code>nagaya-jawiki</code></a> - 「A thing in which several dwelling units are joined in a row horizontally and share walls. Put another way, a single building divided horizontally, each part made an independent dwelling.」 (translated from the Japanese by this project; original: 「複数の住戸が水平方向に連なり、壁を共有する物。別の言い方をするなら、1棟の建物を水平方向に区分し、それぞれ独立した住戸とした物。」)",
 "fn-3": "<a href=\"https://ja.wikipedia.org/wiki/%E9%95%B7%E5%B1%8B\"><code>nagaya-jawiki</code></a> - 「In the Edo period in urban areas, especially dense ones like Edo, merchant houses of the middle level and above kept independent shops on the main street, but the rest of the townsfolk and craftsmen almost all lived as tenants in nagaya in the back streets.」 (translated from the Japanese by this project; original: 「江戸時代において都市部、とくに稠密な江戸などでは中層以上の商家などは表通りに独立した店を構えていたが、それ以外の町人、職人などはほとんどが裏町の長屋に借家住まいだった。」)",
 "fn-4": "<a href=\"https://ja.wikipedia.org/wiki/%E4%BA%AC%E7%94%BA%E5%AE%B6\"><code>kyomachiya-jawiki</code></a> - 「There is also a theory that the shape was a reaction to taxation that treated a three-ken (about 5.4 m) frontage as one household's share. In fact, however, the Edo-period Kyoto tax system, regardless of frontage width, first assessed a total on the town, which the house-owning townsmen making up that town then divided among themselves - that is, a system of so much per house.」 (translated from the Japanese by this project; original: 「また三間（約5.4m）の間口を一軒役として課税したことへの反発した形状とする説もある。しかし実際は、江戸時代の京都の税制は、間口幅に関係なく、まず町に対し総額が賦課され、それを、その町を構成する家持町人が分担する、つまり１軒いくらで負担する制度であった。」)",
 "fn-5": "<a href=\"https://www.kyototuu.jp/Life/ProverbUnaginoNedoko.html\"><code>kyototuu-unagi</code></a> - 「Many machiya are said to have had a frontage of around 2 ken (about 3.6 m) and a depth of 10-12 ken (about 18-22 m).」 (translated from the Japanese by this project; original: 「多くの町家が、間口２間（約３.６m）前後、奥行１０〜１２間（約１８〜２２m）だったといわれる」)",
 "fn-6": "<a href=\"https://ja.wikipedia.org/wiki/%E7%81%AB%E9%99%A4%E5%9C%B0\"><code>hiyokechi-jawiki</code></a> - 「Hiyokechi are fire-prevention open lots that the Edo bakufu established in Edo, prompted by the Great Meireki Fire of Meireki 3 (1657).」 (translated from the Japanese by this project; original: 「火除地（ひよけち）とは、江戸幕府が明暦3年（1657年）の明暦の大火をきっかけに江戸に設置した防火用の空地」) / 「After that fire, five burned-over sites were assigned as hiyokechi, and thereafter, mainly to keep fire from spreading to Edo Castle, they were added little by little, centered on the castle's northwest side, growing to as many as 13 sites by the Kyoho era.」 (translated from the Japanese by this project; original: 「同大火後に焼け跡5ヶ所を火除地に充てた他、以後も主として江戸城への類焼を防止する観点から江戸城の北西側を中心に少しずつ増やされて享保年間には13ヶ所にも増大された。」) (the page never discusses the spacing of individual houses.)",
 "fn-7": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「The Ta-ming Hu, a recreational lake in Tsinan, the capital of Shantung, occupied about one-fifth of the total area enclosed by the original city wall.」 (p. 95) (English; supports 009's \"Jinan's lake = ~1/5 of the walled area\".)",
 "fn-8": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「Assuming four gates, we may now look at the street grids associated with them. The most regular is a Latin cross formed by two streets connecting the four gates (see Figure 5, model a). The city's drum tower is typically located at the central intersection.」 / 「A second general pattern departs from the first in omitting the northern half of the north-south thoroughfare, so that the street running north from the south gate forms a T with the east-west thoroughfare (see Figure 5, model b). In most cases, this street pattern is associated with a north-central location of the yamen and other official buildings」 (p. 97) (English. Also p. 97: 「The majority of city plans, however, show a clear-cut preference for avoiding an uninterrupted thoroughfare running straight from one gate to another」 - i.e. the cross and T are the REGULAR models, and most plans actually deflect the trunk (Figure 5 models c-e; \"the main street leading inward from each of the four land gates ends in a T\", p. 98). The clause \"everything else lanes\" is not on the page - Chang says nothing about the secondary street net.)",
 "fn-9": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「A city's ability to last out a military siege or cut itself off from rural disorder was greatly enhanced by intramural agriculture and an assured water supply.」 (p. 94) / 「Cities built large because of their high administrative level or rank, yet that failed to develop important commercial functions, were inevitably left with large tracts of intramural land that could be devoted to agriculture, whether or not self-sufficiency in case of siege was an initial consideration.」 (p. 95) (English. \"Gardens\" is not Chang's word - he says cultivation, parks, lakes, ponds; \"parks ... preserved for the most part for the use of the aristocracy, officials, and local gentry\" (p. 95).)",
 "fn-10": "<a href=\"https://www.kyototuu.jp/Life/ProverbUnaginoNedoko.html\"><code>kyototuu-unagi</code></a> - 「because tax was levied according to the width of a house's frontage, it is said that frontages were narrowed and deep 'eel's bed' style machiya were built to save tax.」 (translated from the Japanese by this project; original: 「家の間口の広さに応じて課税をしたことで、間口は狭くして、奥行きのある「鰻の寝床」様式の町家を建てて節税をしたといわれる」) (The \"traded dimension\" half is on no page read.)<!-- Same caveat as above: the record's own L21 correction says the tax is not the reason to cite, and this sentence in the second entry still states it as fact; the roster line points to the correction. -->",
 "fn-11": "<a href=\"https://www.kyototuu.jp/Life/ProverbUnaginoNedoko.html\"><code>kyototuu-unagi</code></a> - 「Many machiya are said to have had a frontage of around 2 ken (about 3.6 m) and a depth of 10-12 ken (about 18-22 m).」 (translated from the Japanese by this project; original: 「多くの町家が、間口２間（約３.６m）前後、奥行１０〜１２間（約１８〜２２m）だったといわれる」)",
 "fn-12": "<a href=\"https://ja.wikipedia.org/wiki/%E4%BA%AC%E7%94%BA%E5%AE%B6\"><code>kyomachiya-jawiki</code></a> - 「There is also a theory that the shape was a reaction to taxation that treated a three-ken (about 5.4 m) frontage as one household's share.」 (translated from the Japanese by this project; original: 「また三間（約5.4m）の間口を一軒役として課税したことへの反発した形状とする説もある。」) (the page does not itself state a typical frontage of 3 ken. Together with the 京町家 page's 「the frontage is narrow and the depth is deep」 (translated from the Japanese by this project; original: 「間口が狭く奥行きが深い」) this is adequate for \"narrow\", weak for \"3 ken typical\".)",
 "fn-13": "<a href=\"https://ja.wikipedia.org/wiki/%E7%81%AB%E9%99%A4%E5%9C%B0\"><code>hiyokechi-jawiki</code></a> - 「fire-prevention open ground that the Edo bakufu established in Edo, prompted by the Great Meireki Fire of Meireki 3 (1657)」 (translated from the Japanese by this project; original: 「江戸幕府が明暦3年（1657年）の明暦の大火をきっかけに江戸に設置した防火用の空地」) / 「In the broad sense it also includes hirokoji and the like - streets made with the same purpose.」 (translated from the Japanese by this project; original: 「広義では、同様の趣旨を持った街路である広小路なども含まれる。」) (the page also lists named ones (両国広小路, 湯島広小路, 御茶水広小路, 中橋広小路 ...).)",
 "fn-14": "<a href=\"https://ja.wikipedia.org/wiki/%E7%81%AB%E9%99%A4%E5%9C%B0\"><code>hiyokechi-jawiki</code></a> - 「After that fire, five burned-over sites were assigned as hiyokechi, and thereafter, mainly to keep fire from spreading to Edo Castle, they were added little by little, centered on the castle's northwest side, growing to as many as 13 sites by the Kyoho era.」 (translated from the Japanese by this project; original: 「同大火後に焼け跡5ヶ所を火除地に充てた他、以後も主として江戸城への類焼を防止する観点から江戸城の北西側を中心に少しずつ増やされて享保年間には13ヶ所にも増大された。」) (it contains no rule about spacing between houses. \"Never spaced individual machiya apart\" is therefore an inference from what the page does NOT say, not a statement it makes.<!-- if the session wants a positive quote for this clause it needs another source. -->)",
 "fn-15": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「As we noted earlier, the higher the rank of an administrative city, the greater the area enclosed by planners in its original walls. High-ranked cities may have been built large in part out of concern for their defensibility, but the more usual consideration was likely to have been the expectation that the natural course of urban development would lead to larger populations in prefectural capitals than in department capitals, in department capitals than in county capitals, and so on.」 (p. 95) (English.)",
 "fn-16": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「In many traditional cities, surprisingly large proportions of the total intramural area were given over to cultivation and to lakes, ponds, streams, canals, springs, and other bodies of water.」 (p. 94) (English; an OCR transcription of the scanned page image, the PDF having no text layer. Supports the qualitative claim that a large share of the walled ground stayed unbuilt; Chang gives no percentage - the 25-30% is this record's own synthesis<!-- specs/009 --> over the named anchors, and the only number on the page is Tsinan's one-fifth.)"
};
