// DERIVED FILE - written by `make citations` from research/citations/cities/hinterland.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "<a href=\"https://publishing.cdlib.org/ucpressebooks/public/book/chinese-local-elites-and-patterns-of-dominance.html\"><code>cdlib-local-elites</code></a> - 「By Qing times, the substantially urbanized gentry were living the leisured life of absentee landlords in administrative centers or the many small towns that lined the canals.」 (the motive - exams, office, social life - is this record's own inference; the passage names none.)<!-- English. NOTE: the page supports \"urbanized gentry living in town as absentee landlords\"; the PULL being \"exam/office/social life\" is the file's inference - the fetch was asked for \"elites moving into cities/towns for examinations, office or social life\" and the returned passage names no motive. Partial support; the motive clause is unquoted. -->",
 "fn-2": "<a href=\"https://publishing.cdlib.org/ucpressebooks/public/book/chinese-local-elites-and-patterns-of-dominance.html\"><code>cdlib-local-elites</code></a> - 「After the Jiangnan landlords moved to towns and cities, there was less of a truly rural, community-oriented elite and few rural militia. Instead, absentee landlords acted in the villages through their agents and rent-collection bursaries supported by county governments.」 (the \"Edo reading\" for Japan has no cited source.)<!-- English. NOTE: this supports the China half (resident in town, land worked through agents). -->",
 "fn-3": "<a href=\"https://zdic.net/hans/%E5%85%B3%E5%8E%A2\"><code>guanxiang-zdic</code></a> - 「The streets outside the city gate and the nearby area.」 (translated from the Chinese by this project; original: 「城门外的街道及附近区域。」) and 「The main street outside the city gate.」 (translated from the Chinese by this project; original: 「城门外的大街。」) (\"The streets outside the city gate and the nearby area.\" / \"The main street outside the city gate.\" (the second is the 國語辭典 definition on the same page). The page also gives 「In antiquity, the lodging-houses (亭舍) near the city walls.」 (translated from the Chinese by this project; original: 「古代城郭附近的亭舍。」) - \"in antiquity, the lodging-houses near the city wall\" - and the Ming-shi example 「Liangyu and Daqi were at odds; their soldiers fought one another privately, and burned the guanxiang (关厢) of Nanchang.」 (translated from the Chinese by this project; original: 「良玉、大器不和，兵私斗，焚南昌关厢。」) - \"Liangyu and Daqi were at odds; their soldiers fought privately and burned the guanxiang of Nanchang.\")",
 "fn-4": "no publicly readable source (searched 2026-09-06: zdic.net's 关厢 entry carries no such passage; Baidu Baike's 关厢 entry does, but refuses automated fetches)<!-- the passage came from registry entry guanxiang-zdic; the passage: 「The merchants of the Jin Zhongdu period considered these places prime money-making ground, because these are transportation hubs, you see, dense with the flow of people.」 (translated from the Chinese by this project; original: 「金中都时的商人们，认为这些地方是生财宝地，因为这是交通枢纽呀，人流密集。」) -->",
 "fn-5": "<a href=\"https://zdic.net/hans/%E5%85%B3%E5%8E%A2\"><code>guanxiang-zdic</code></a> - 「In antiquity, the lodging-houses (亭舍) near the city walls.」 (translated from the Chinese by this project; original: 「古代城郭附近的亭舍。」) (the entry gives the lodging houses only; that markets and inns grew outside a busy gate is quoted at note 7, and the SIZE of the belt is still a guess.)",
 "fn-6": "no publicly readable source (searched 2026-09-12: no work was named for the claim, and the source pass found no public page saying that the ground just below a field's drainage collector is the wettest in a valley and is left unbuilt)<!-- the ring behavior beside it is a measurement of the drawn capital, not a source -->",
 "fn-7": "<a href=\"http://web.stanford.edu/~mel1000/sen.pdf\"><code>chang-morphology-walled-capitals</code></a> - 「Since gates channeled all traffic to and from a sector of the city's hinterland, the areas immediately outside them were favored sites for markets and businesses serving the rural populace. Inns and other services catering to travelers and traders were established outside the particular gates that gave access to long-distance routes.」 and 「It should be noted explicitly that in many if not in most cities, suburbs outside the most frequented gates developed before the intramural area had been completely built up.」 (p. 99; the passages carry the pattern - what kind of thing grew outside a gate, and which gates drew it - and no count of structures.)",
 "fn-8": "no publicly readable source (searched 2026-09-12: the Stanford copy of Chang's \"The Morphology of Walled Capitals\" was gone through page by page and gives the gate suburb's pattern but no number of structures; the zdic entry for 关厢 carries the word's definition only)<!-- the ten-to-forty figure came from a 2026-07-22 project note of general reading and from Beijing's 大关厢; neither is a page a reader can check it on -->",
 "fn-9": "no publicly readable source (searched 2026-09-12: no work was named for the in-wall vegetable tract - its well water, its night soil, or its share of the enclosed ground - and the source pass found none)<!-- Chang p. 94 supports intramural CULTIVATION in general; it says nothing of garden tracts, wells or night soil, so it is not cited here -->",
 "fn-10": "no publicly readable source (searched 2026-09-12: no work was named for the handedness of a field's irrigation fan, and the source pass found no public page on which either hand is attested)<!-- the mirroring is a fit to the pocket the ring road leaves, calibrated against the drawn cities -->",
 "fn-11": "no publicly readable source (searched 2026-09-12: no work was named for the size of an urban kitchen-garden bed, and the source pass found none)<!-- the 55 ft is a calibration against the drawn cities: smaller than the grain hem's 90-100 ft strip, and an even number of columns across the tract -->",
 "fn-12": "no publicly readable source (searched 2026-09-12: no work was found pricing a city wall against the ground it encloses, or stating that farmland was what a wall was drawn around rather than through)<!-- Chang pp. 94-95 says the opposite of half of it: large intramural tracts WERE farmed where a city was walled above its growth -->"
};
