// DERIVED FILE - written by `make citations` from research/citations/cities/river-cities.html (feature 211). Never
// edit here: change the note on the citations page and run `make citations`; the gate fails while the two differ.
window.RECORD_CITATIONS = {
 "fn-1": "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7048742/\"><code>kaifeng-pmc7048742</code></a> - 「SRTM 90 m DEM of the area around Kaifeng, note that the elevation of the Yellow River is higher than Kaifeng」 (Figure 1 caption) (English; supports the bed standing above the city, but \"meters\" is not quantified on the page - the number is the record's own)",
 "fn-2": "<a href=\"https://en.wikipedia.org/wiki/1642_Yellow_River_flood\"><code>kaifeng-flood-1642-enwiki</code></a> - 「300,000 of the 378,000 residents were killed by the flood and ensuing peripheral disasters such as famine and plague.」 (English. Corroborated by the PMC paper: 「According to The Veritable Documents of the Ming, in AD 1642 a large army breached the dikes along the Yellow River to intentionally flood the city, killing nearly 300,000 people.」 Note: en.wikipedia's Kaifeng article gives different figures - 「Only 30,000 of the 370,000 people in the city remained.」)",
 "fn-3": "<a href=\"https://okayama-castle.jp/learn-history-en/\"><code>okayama-castle</code></a> - 「In addition, the branching channels of the Asahi River were devised as they are today to protect the north and east sides of the castle and utilized to create moats, and a castle town was built that stretched long in the north-south direction between the moats.」 (English; supports the Asahi serving as the moat on two flanks.<!-- The quoted phrase \"natural moat\" does NOT appear on the page - the quotation marks are unearned -->)",
 "fn-4": "<a href=\"https://en.wikipedia.org/wiki/Pan_Gate\"><code>pan-gate-enwiki</code></a> - 「Pan Gate at the southwest corner of the city's central historic district, with the water gate connecting the city's inner canals and former defensive moat with the nearby Grand Canal.」 (English; supports a water gate admitting a canal at Suzhou; that this is the only way water enters a wall is our inference, not on the page)",
 "fn-5": "<a href=\"https://en.wikipedia.org/wiki/Pan_Gate\"><code>pan-gate-enwiki</code></a> - 「It consists of a section of the old Suzhou City Wall that includes two separate gates, one opening to a road for pedestrian and vehicular traffic and another opening to a canal for waterborne vessels. It is thus sometimes known as Suzhou's Land and Water Gate.」 「It is thus sometimes known as Suzhou's Land and Water Gate.」 (English)",
 "fn-6": "<a href=\"https://en.wikipedia.org/wiki/Pan_Gate\"><code>pan-gate-enwiki</code></a> - <!-- SUMMARY-ONLY - the registry records \"the sluiced arch is SUMMARY-ONLY (chinahighlights)\"; --> the Wikipedia page has no sentence on a sluice, arch or portcullis (the only structural detail is the Wu Gate Bridge: 「the highest bridge of the ancient city, allowing barges and other boats to more easily pass below」)<!-- no chinahighlights URL is registered under the key, so nothing to fetch -->",
 "fn-7": "<a href=\"https://en.wikipedia.org/wiki/Pan_Gate\"><code>pan-gate-enwiki</code></a> - 「with the water gate connecting the city's inner canals and former defensive moat with the nearby Grand Canal」 (English)",
 "fn-8": "<a href=\"https://zdic.net/hans/%E5%85%B3%E5%8E%A2\"><code>guanxiang-zdic</code></a> - 「The streets outside the city gate and the nearby area.」 (translated from the Chinese by this project; original: 「城门外的街道及附近区域」); 「In antiquity, the pavilion-lodges near a walled city.」 (translated from the Chinese by this project; original: 「古代城郭附近的亭舍」) (\"the streets outside the city gate and the area near them\"; \"in antiquity, the lodges near a city's walls\". Supports guan-xiang = the district outside a gate; that it was a MARKET is a GUESS - no readable page supports it (Baidu Baike, 403) and the zdic page has no sentence on commerce)",
 "fn-9": "<a href=\"https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7048742/\"><code>kaifeng-pmc7048742</code></a> - 「Despite Kaifeng’s political and economic importance, the Yellow River has flooded Kaifeng around 40 times over the past 3000 years.」 (English)",
 "fn-10": "<a href=\"https://en.wikipedia.org/wiki/Kaifeng\"><code>kaifeng-enwiki</code></a> - 「Five major floods devastated the city between 1375 and 1416, and flooding occurred more than 300 times from the Southern Song Dynasty to the late Qing dynasty.」 (English. Also on the page, for the 1642 event: 「During the third siege, Kaifeng was flooded by the Ming army by the Yellow River to drown the rebels. The entire city was submerged in several feet deep water.」)",
 "fn-12": "<a href=\"https://ja.wikipedia.org/wiki/河岸\"><code>kashi-jawiki</code></a> - 「Once the Edo period began, merchants carrying on wholesale trade (tonya) and their storehouses (kura) gathered at the kashi, forming a single commercial settlement.」 (translated from the Japanese by this project; original: 「江戸時代に入ると河岸には問屋を商う商人やその蔵が集まり、一つの商業集落を形成していた」); 「At the center that managed the kashi stood the kashi-donya (riverbank wholesaler) or the funa-donya (ship wholesaler). The kashi-donya took fees called kosen and niwasen, charged for such things as unloading and loading ships and storing cargo.」 (translated from the Japanese by this project; original: 「河岸を仕切る中心として河岸問屋または船問屋があった。河岸問屋は、船の荷揚げや荷積み、荷物の保管などによる口銭や庭銭とよばれる手数料をとっていた」) (\"from the Edo period, wholesale merchants and their storehouses (kura) gathered at the kashi, forming a commercial settlement\"; \"at the center of a kashi was the kashi-donya or ship-donya, which took fees called kosen and niwasen for unloading, loading and storing cargo\". \"Directly behind the bank street\" is not stated<!-- supports kura at the kashi -->)"
};
