#!/usr/bin/env python3
"""Kashikawa (樫川, "oak river") - the SCRIPTED hamlet at the top of the size band.

Generated by [`hamletgen.py`](../../hamletgen.py) rather than authored: this file declares a name, a
seed, a household count, the land's fall and where the runoff goes, and every position on the map -
the intake, the field's size, the cluster, the lanes, the connector track, the woods, the
windbreak - is derived from those by the pipeline. Nothing here is a coordinate.

The brief: 20 households - the ceiling of the hamlet band - on land falling northeast
(`down_deg=315`), the collector's brook running off the map (`water_sink="offmap"`). It exists to
show the pipeline at the top of the band, where the cluster, the well count and the paddy acreage
are all at their largest. See `kashikawa.notes.md` for the kanji triangle and the review log.


ONE DECLARED KNOB, and the reason it is declared (feature 230): `brook_side=-1` - the brook passes the fan on
the flank the drain's outfall stands on, so the collector reaches it and the two join at a confluence the sheet
shows. The flank is otherwise rolled, and this seed rolls the other one, which puts the brook uphill of the
outfall and sends the drain off the frame on its own. The confluence is the third of the feature's three water
sinks and the one the research turned on - before modern consolidation a village's drainage went back to the
watercourse to be taken up by the district below - and an implemented sink owes one map that exhibits it, the
way a knob owes one map per value. Sawada was tried first and cannot take it at any flank: its outfall stands
at the canvas edge, so the brook has about 85 px left below the junction against the 150 the rule asks
(specs/230 research R7). Measured here, on the view box: the junction falls 123 ft inside the view with 177 ft of the
brook visible below it.

THE SEED IS 8, NOT 3 (feature 261). The wind is the regional northwest unless a map declares one, and the
cluster is seated with its back to it. At seed 3 no clean margin whose back faces the wind was open - the west
margins back onto the dry hem, the northwest ones stand in the wet toe, the rest are crossed by the brook this
map's declared flank runs along - so the seat fell back off the wind and the belt came out with no trees at all,
the very thing the GM asked about. A seed is a roll, not a fact about the place, so the map was re-seeded with
its fall, its sink and its brook flank kept: over seeds 1-30, five seat all twenty households on a clean
wind-facing margin; of those, 14 drew the fullest belt but wrapped it 333 degrees round the houses, and 8 draws the next fullest (264 clumps, west-northwest, a 134-degree arc) (specs/261 research R4).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))  # <tree>/<tier>/<map>/ - one level deeper since feature 161 gave every map its own folder
sys.path.insert(0, SKILL)
from l7r.diagram.hamletgen import HamletSpec, generate  # noqa: E402

report = generate(HamletSpec(name="Kashikawa", seed=8, households=20, down_deg=315, water_sink="offmap", brook_side=-1), out_base=os.path.join(HERE, "kashikawa"))
print(report.line())
