#!/usr/bin/env python3
"""Kuwabata (桑畑, "mulberry field") - the MULBERRY-DIKE FISH-POND hamlet, SCRIPTED (feature 139).

Generated by `hamletgen` from the declaration below, as Inashiro is: a name, a seed, a household
count, the land's fall, the archetype and the one form knob the GM saw. Every position - the polder
grid fitted to the acreage, the header reservoir at the high corner, the perimeter dike and its
sluices, the ponds and their mulberry banks, the village on the landward dike, the reed fringe on
the water-facing flanks, the lanes, the fixtures, the bamboo, the windbreak - is derived. Nothing
here is a coordinate. The hand-authored script it replaces (2026-07-24 to 2026-08-27) is in git
history at the commit before this one; `kuwabata.notes.md` carries the design record.

THE ARCHETYPE: polder GEOMETRY (build_polder - the wei-tian 圩田 polders of the lower-Yangtze lake
plains) carried to the dike-pond system's rare WHOLESALE-CONVERSION end state (桑基魚塘,
`apply_land_use(eligible="all")`): (almost) every former paddy cell dug into a fish pond and the
spoil piled into a mulberry-planted dike around it. See research/archetypes.md "The three overlay
values" for why the end state is the exception and the scattered overlay the norm.

ECONOMY (GM-confirmed 2026-07-24): a cash-crop settlement, not a subsistence one - the rice-farmer's
analog of the tobacco/indigo switch. Stocked carp ponds; the loop is mulberry leaf -> silkworm ->
frass -> fish -> dredged pond mud -> dike fertility; silk is the bigger earner, fish go to market,
grain is bought in. Gazetteers found the total absence of rice remarkable enough to record.
Placement implication: a river or canal link to a substantial market town is implied wherever
Kuwabata sits. Open flavor hook, NOT canon anywhere wider: L7R land tax is assessed in koku of
rice, so Kuwabata's tax is presumably commuted to cash or silk.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, SKILL)
from l7r.diagram.hamletgen import HamletSpec, generate  # noqa: E402

# seed 21 and 16 households are the hand-authored map's; `pond_layout="mosaic"` pins the form the
# GM accepted on it (the Pearl-delta accreted mosaic; the knob also rolls the surveyed grid).
report = generate(HamletSpec(name="Kuwabata", seed=21, households=16, down_deg=90, field_archetype="mulberry_dike_fishpond", pond_layout="mosaic"), out_base=os.path.join(HERE, "kuwabata"))
print(report.line())
