"""The glossary the map's explanations use (feature 134, GM 2026-08-28: "a glossary of terms defined so
that when we use those terms in our modals ... someone can hover their mouse over it to get an
explanation of the word ... 'bund' or 'coppiced', but also any Japanese words that are not so common
that we would expect everyone to know them").

Each entry: the term as it appears in the prose (matched whole-word, case-insensitive, with the
listed variants) and a one- or two-sentence definition. The page wraps every occurrence in the
explanation text in a hover tooltip. Definitions are written from the research entries the
explanations cite; a term here is a term the prose in `classes.py` actually uses.
"""

from __future__ import annotations

import json

#: term -> (variants matched in the prose, the definition)
GLOSSARY: dict[str, tuple[tuple[str, ...], str]] = {
    "bund": (
        ("bund", "bunds", "aze"),
        "The low earthen ridge between two paddy basins, a foot or two wide and about a foot high, re-plastered each spring so each basin holds its water; farmers walk the bunds to reach the plots.",
    ),
    "azemame": (("azemame",), "Bund beans: soybeans planted along the top of a paddy bund, a second crop from ground that would otherwise grow weeds."),
    "coppice": (
        ("coppice", "coppiced", "coppicing"),
        "A wood cut on a cycle - every 15 to 20 years the stems are cut to the stump and regrow - for firewood, poles and fodder; the floor stays open and the canopy young.",
    ),
    "iriai": (("iriai",), "The customary common land of a Japanese village - woods, grass and scrub held by the village and governed by its own rules on who may cut, when, and how much."),
    "satoyama": (("satoyama",), "The managed country between the village and the mountain: the coppice woods, grasslands, paddies and ponds a farming community worked and drew on."),
    "tameike": (("tameike",), "An irrigation reservoir - a pond made by damming a valley head with an earthen dike, sitting above the fields it waters, with a single outlet."),
    "yashikirin": (("yashikirin",), "A homestead grove: the belt of trees planted around a farmhouse plot as its own shelter from wind and sun."),
    "fengshui grove": (
        ("fengshui forest", "fengshui back grove", "fengshui grove", "fengshui"),
        "The grove a village keeps on its windward, high side - the back grove of Chinese village planning - as its wall against the winter wind.",
    ),
    "hokora": (("hokora",), "A small roadside or household shrine, a knee-high shelter of stone or wood for a local spirit."),
    "kosatsuba": (("kosatsuba",), "The notice board: a small roofed frame where the authorities posted the standing law, rate tables and ban lists, sited where everyone passes."),
    "minka": (("minka",), "A traditional Japanese farmhouse - a timber-framed dwelling under a steep thatched roof, its ridge on the long axis."),
    "take-yabu": (("take-yabu",), "A bamboo thicket: a clonal stand of bamboo with a hard edge, held and cut like a coppice."),
    "shitsuden": (
        ("shitsuden",),
        "Wet paddy: rice ground too poorly drained to dry out, which holds water even out of season. Harder to work, colder, and lower-yielding than a paddy that can be emptied, and it takes no winter crop.",
    ),
    "kanden": (("kanden",), "Dry paddy: rice ground that drains, so that when the water is let out it dries to an ordinary dry field and can carry a winter crop before the next flooding."),
    "hatake": (("hatake", "hata"), "Dry-field farmland - the unirrigated ground that grows grains, beans and vegetables, as against the flooded paddy."),
    "goemon-buro": (("goemon-buro",), "The cauldron bath: an iron tub heated from below, the bath of self-sufficient farm villages."),
    "magariya": (("magariya",), "The L-shaped farmhouse of northern Japan, with the stable under the same roof as the dwelling - a cold-country form."),
    "daizu": (("daizu",), "The soybean - grown as a field crop of its own on the dry hem, and along the paddy bunds as azemame."),
    "catena": (("catena",), "The sequence of soils and crops down a slope: paddy on the wet valley floor, dry crops on the well-drained ground above, woodland on the hill."),
    "hem": (("hem",), "The band of dry ground above the paddy's supply canal where the dry crops grow."),
    # Feature 205 (GM 2026-09-07). Written from the record the threshing yard cites - research/homesteads.html,
    # "How big was the work yard, and how did the sizes spread?": two straw mats to the tsubo (fn 12), a mat
    # 3 x 6 shaku, 90 x 180 cm (fn 15) - so one ken square, the 59.5 sq m the explanation gives for 18 tsubo.
    "tsubo": (
        ("tsubo",),
        "The Japanese unit of area, a square about six feet on a side - the floor of two straw mats laid side by side, about 3.3 square meters (36 square feet). House floors and work yards were counted in it.",
    ),
    "head race": (("head race", "head-race",), "The channel that carries water from the intake along the field's high edge to where it is divided into the ditches."),
    "lateral": (("lateral", "laterals"), "A branch ditch running down-slope from the head race between the plots."),
    "polder": (("polder",), "Land reclaimed from marsh or lake behind an enclosing dike and drained by canals."),
    "night soil": (("night soil",), "Human waste collected from privies and composted as fertilizer."),
    "dooryard": (("dooryard",), "The yard at a farmhouse's door - the household's own ground beside the house."),
    "toe": (("toe",), "The low foot of a slope or a field, where the water collects."),
    # THE RECORD'S VOCABULARY (feature 209, GM 2026-09-07: *"having a tool tip with the actual definition of this
    # would be helpful"*). From here down, terms the research pages use that a casual reader would not know - the
    # Japanese and Chinese words of farming, water, building, caste and government, and the units. Each definition
    # is written from the record's own entries (the file that uses the term most is the one to read); a term used
    # by no modal and no page fails `test_the_glossary_is_well_formed_and_used`.
    "kainyo": (("kainyo",), "The Tonami plain's own word for a homestead grove: the stand of cedar and other trees wrapped around each of its dispersed farmsteads."),
    "igune": (("igune",), "The northern (Tohoku) word for a homestead grove - the belt of cedar, pine, cypress and zelkova on a farmhouse's north and west."),
    "sugi": (("sugi",), "Japanese cedar: the tall, straight conifer planted for timber and shelter, and the mainstay of a homestead grove."),
    "jokamachi": (("jokamachi",), "A castle town: the settlement laid out below a lord's castle, its samurai, townspeople and temples each zoned to their own wards by rank."),
    "daimyo": (("daimyo",), "A domain lord: the hereditary ruler of a domain held from the shogunate, ranked by the assessed rice yield of their land."),
    "bakufu": (("bakufu", "shogunate"), "The shogun's government - the military administration that ruled Japan over the heads of the domain lords."),
    "hatamoto": (("hatamoto",), "A direct retainer of the shogun, ranking below a domain lord and above ordinary samurai."),
    "bushi": (("bushi",), "A warrior of the samurai class; the word the sources use for the class as a whole."),
    "ashigaru": (("ashigaru",), "Foot soldiers, the lowest rank of samurai, housed together in row houses at a castle town's outer edge."),
    "nagaya": (("nagaya",), "A row house: one long building divided along its length into small tenements, each a room or two deep."),
    "ashigaru-nagaya": (("ashigaru-nagaya",), "The foot soldiers' row housing at a castle town's outer edge - the town's outermost ring of defense as well as its cheapest samurai housing."),
    "nagayamon": (("nagayamon", "nagaya-mon"), "A gate cut through a long row building: a samurai residence's front range, with the gatekeeper's room, servants' quarters, stable and storeroom inside it."),
    "kumi-yashiki": (("kumi-yashiki",), "Group residences: a block of plots where one squad of retainers lived together, on a castle town's fringe."),
    "kumi": (("kumi",), "A group: a squad of foot soldiers, or a neighborhood association of households answerable together."),
    "yashiki": (("yashiki",), "A residence plot - a samurai's mansion lot in a town, or a farmer's homestead lot in a village."),
    "chugen": (("chugen",), "Samurai household servants of commoner birth, hired by the season or the day."),
    "chonin": (("chonin",), "Townspeople: the merchants and artisans of a castle town's commoner wards."),
    "machiya": (("machiya",), "A townhouse: a merchant's or artisan's house on a narrow street frontage and a deep lot, shop at the front and living quarters behind."),
    "kura": (("kura", "dozo"), "A storehouse with thick plastered earthen walls, built to keep grain and goods through a fire that takes the wooden buildings around it."),
    "yagura": (("yagura",), "A tower or turret - on a castle wall, or a town's lookout for fires."),
    "hinomi-yagura": (("hinomi-yagura",), "A fire lookout tower: a town's tall timber watch tower with a bell, from which a fire brigade was called out."),
    "masugata": (("masugata",), "A castle gate court: a square enclosure between two gates set at right angles, so that whoever comes through the first must turn under fire before the second."),
    "sotobori": (("sotobori",), "A castle's outer moat, ringing the town's inner wards rather than the castle itself."),
    "honmaru": (("honmaru",), "The innermost bailey of a Japanese castle, where the keep and the lord's palace stand."),
    "ninomaru": (("ninomaru",), "The second bailey of a Japanese castle, outside the innermost one, often holding the lord's palace and offices."),
    "sannomaru": (("sannomaru",), "The third bailey of a Japanese castle, outermost of the three, holding the senior retainers' mansions and offices."),
    "tenshu": (("tenshu",), "The keep: the tall tower at the heart of a Japanese castle - a fraction of the whole fortified area, which is mostly baileys and moats."),
    "goten": (("goten",), "A palace: the lord's residence and offices, standing inside the castle's baileys."),
    "jin'ya": (("jin'ya", "jinya"), "The seat of a small domain or of a shogunate intendant: an unfortified compound of residence, offices, retainers' houses and storehouses, in place of a castle."),
    "daikan": (("daikan",), "An intendant: the magistrate who administered a tract of the shogunate's own land from a local office."),
    "daikansho": (("daikansho",), "An intendant's office: the compound from which a tract of the shogunate's own land was administered - the model for the setting's county magistracy."),
    "hanko": (("hanko",), "A domain school: the academy where a domain educated its samurai, one in nearly every domain by the end of the Edo period."),
    "dojo": (("dojo",), "A martial-arts training hall - a city institution; in the country, samurai trained in a yard or a cleared hall."),
    "machi-dojo": (("machi-dojo",), "A private commercial training hall in a city, run for fees by low-ranking samurai and later by commoners."),
    "bugeijo": (("bugeijo",), "A domain's martial training ground, where its samurai drilled."),
    "shoya": (("shoya", "nanushi"), "A village headman: the villager who answered to the domain for the village's taxes, registers and order."),
    "kokudaka": (("kokudaka",), "A holding's assessed yield in koku of rice - the number every domain, village and stipend was measured by, whatever the land actually grew."),
    "koku": (("koku",), "About 180 liters of rice: the unit of assessed yield, tax and stipend, taken by convention as a year's food for one adult."),
    "tan": (("tan",), "A tenth of a cho, about 992 square meters: the strip a paddy was reckoned in."),
    "cho": (("cho",), "About one hectare (10 tan), the unit a holding or a village's fields were reckoned in; also a town block of that size."),
    "shinden": (("shinden",), "New fields: land reclaimed and settled by allotment in the Edo period, each household given a homestead and a strip."),
    "mushiro": (("mushiro",), "A straw mat, about 90 by 180 centimeters - two to a tsubo - spread over the work yard to dry the harvest, and the unit the yard was measured in."),
    "hazakake": (("hazakake", "hasa"), "Rice-drying racks: poles in the field on which the cut sheaves hang for a week or two before threshing."),
    "kichin-yado": (("kichin-yado",), "A cheap communal lodging in a town, the 'firewood-fee inn': a traveler slept on straw under a roof for a small fee toward the fire."),
    "fudasashi": (("fudasashi",), "Rice brokers of the shogun's capital who warehoused the samurai's stipend rice, converted it to cash and lent against it."),
    "kuramai": (("kuramai",), "Stipend rice: the rice a domain paid its samurai out of the domain granary."),
    "kayabuki": (("kayabuki",), "Thatch roofing of reed or grass, the covering of nearly every farmhouse."),
    "kawaramono": (("kawaramono",), "'Riverbed people': the outcast tanners' own name for themselves, from the riverside ground their quarter stood on."),
    "kakehi": (("kakehi",), "An aqueduct: a wooden flume carrying an irrigation channel over a stream or a gully."),
    "mizuguchi": (("mizuguchi",), "A paddy's intake: the notch in the bund through which water enters the plot from the delivery ditch, one per plot."),
    "shirimito": (("shirimito",), "A paddy's outlet: the overflow notch in the bund, set a little below the field surface, through which surplus water leaves the plot."),
    "azenuri": (("azenuri",), "The spring re-plastering of the paddy bunds with puddled mud, so that each basin holds its water."),
    "yaita": (("yaita",), "Sheet boards driven along a bank or a bund to hold its face."),
    "torii": (("torii",), "A Shinto shrine gate: two posts and two lintels. Each is a donor's gift, so a well-patronized shrine has rows of them."),
    "kannushi": (("kannushi",), "A Shinto shrine priest, usually a hereditary office within one family."),
    "jinja": (("jinja",), "A Shinto shrine: the sanctuary of a local deity, with its gate, approach and hall."),
    "tatami": (("tatami",), "A straw floor mat about 90 by 180 centimeters; a room's size is counted in them."),
    "doma": (("doma",), "The earth-floored working half of a farmhouse, where the hearth, the kitchen work and the animals were."),
    "engawa": (("engawa",), "The veranda running along the outside of a house's rooms, under the eaves."),
    "genkan": (("genkan",), "The entry of a house: the step up from the ground to the floored rooms, where shoes come off."),
    "ton'ya": (("ton'ya", "tonya", "toiya"), "A wholesaler-warehouseman of the Edo economy, who stored, sold on and shipped a trade's goods."),
    "sekisho": (("sekisho",), "A barrier station on a highway, where travelers and their goods were inspected."),
    "kawara": (("kawara",), "Roof tile: fired clay tile, general on towns' roofs only at the end of the Edo period; commoners' houses were board- or thatch-roofed."),
    "burakumin": (("burakumin",), "The hereditary outcast community of Japanese history, who did the tanning, the executions and the other work the other castes would not; their quarter stood at the settlement's edge, by water."),
    "heimen": (("heimen", "heimin"), "The setting's commoner caste - farmers, artisans and merchants - who in the Celestial Order are 'half-people', below the samurai."),
    "hinin": (("hinin",), "The setting's outcast caste, 'non-people' in the Celestial Order, below even the commoners."),
    "yamen": (("yamen",), "The walled office compound of a Chinese county or prefectural magistrate: court, offices and residence in a run of courtyards on one axis."),
    "mu": (("mu",), "A Chinese land unit of about 667 square meters, roughly a fifteenth of a hectare."),
    "ken": (("ken",), "A Japanese unit of length of about 1.8 meters - the bay between two posts of a building, and the unit a lot's frontage was measured in."),
    "shaku": (("shaku",), "A Japanese foot of about 30 centimeters; ten to a jo, six to a ken."),
    "cun": (("cun",), "A Chinese inch of about 3.3 centimeters; ten to a chi."),
    "chi": (("chi",), "A Chinese foot of about 33 centimeters; ten cun."),
    "tangpu": (("tangpu",), "The dike-and-canal grid of a Chinese polder district, its canals five to ten li apart."),
    "jori": (("jori", "jori-sei"), "The ancient Japanese land grid laid over the settled plains: one-cho squares, each cut into strips of one tan."),
    "hyō": (("hyō", "hyo", "tawara"), "A straw bale: the unit rice, charcoal and salt were packed and counted in - of no fixed weight for charcoal."),
    "yosui": (("yosui",), "An irrigation canal - a district's main supply channel, which forks downstream into the ditches that water the fields."),
    "akusui": (("akusui",), "The drain: the collector ditch at a field's foot that gathers the paddies' tail water and storm runoff, wider at its end than the supply that watered the same ground."),
    "delivery ditch": (("delivery ditches", "delivery ditch"), "The ditch running down from a supply canal between the plots, feeding each paddy through one intake and thinning as it sheds its water."),
    "collector": (("collector",), "The drain along a field's low line that gathers what runs out of the basins."),
    "tagoshi kangai": (("tagoshi kangai",), "Plot-to-plot irrigation: water enters the head paddy of a string and cascades through the bunds from one plot to the next, so the interior plots have no ditch of their own."),
    "maoqu": (("maoqu",), "The last of China's five fixed canal grades: the small ditch that carries water into each individual plot."),
    "bunsuiguchi": (("bunsuiguchi",), "A division point: where a head race splits into the branch ditches that water each side of a field."),
    "offtake": (("offtakes", "offtake"), "The point where a smaller channel leaves its parent, at an acute angle pointing downstream."),
    "command area": (("command area",), "The ground an irrigation system can reach by gravity from its intake - everything below the head race that the ditches can water."),
    "wetted perimeter": (("wetted perimeter",), "The length of a channel's cross-section that is in contact with the water; a canal's width follows the square root of its flow through it."),
    "freeboard": (("freeboard",), "The height of bank kept above the water surface, so a full channel does not spill."),
    "berm": (("berms", "berm"), "The bare strip of embankment top between a canal and the nearest plot, about a meter wide - room to stand for the yearly dredging."),
    "stilling pool": (("stilling pool",), "A basin below an intake that calms the incoming water before it enters the channel."),
    "weir": (("weirs", "weir"), "A low dam across a channel that holds a set water level and sheds only the surplus over its crest."),
    "sluice": (("sluices", "sluice"), "A gated opening in a bank or dam that controls how much water passes."),
    "puddling": (("puddling", "puddled"), "Working the flooded paddy soil into a smooth, water-holding mud before transplanting - the peak of a paddy's water demand; a bund is puddled mud."),
    "alluvial fan": (("alluvial fans", "alluvial fan"), "The spread of gravel a stream lays down where it leaves the hills: a steep apex, a dry mid-fan where the water sinks into the gravel, and a spring line at its toe."),
    "spring line": (("spring line",), "The belt at the toe of an alluvial fan where water that sank into the gravels re-emerges; settlements and paddies cluster there."),
    "backswamp": (("backswamps", "backswamp"), "The low, poorly drained ground behind a river's natural levees, where floodwater stands and mud settles."),
    "natural levee": (("natural levees", "natural levee"), "The slightly raised bank a river builds along its own channel from the coarse sediment it drops first - the first-settled dry ground of a floodplain."),
    "yato": (("yatsuda", "yachida", "yato"), "A narrow spring-fed valley head cut into a plateau; its bottom paddies, developed early, were as much managed marsh as field."),
    "fukada": (("fukada",), "A 'deep field': a paddy with deep, soft mud that mires to the knee, poorly drained until modern works."),
    "numajiro": (("numajiro",), "A 'marsh castle': a fort whose surrounding wetland was its main defense."),
    "glacis": (("glacis",), "The open slope before a fortification that an attacker must cross exposed; the flooded paddies around a castle town served as one."),
    "corvee": (("corvee",), "Labor owed to a lord in place of tax - the work that built a town's moats, dikes and canals."),
    "sara-ike": (("sara-ike",), "A 'dish pond': a shallow lowland reservoir ringed by embankments, as against the valley-head pond behind one dam."),
    "Meiji": (("Meiji",), "The era from 1868, when Japan modernized: its land consolidation, drainage works and row planting are the modern forms a pre-modern map must not show."),
    "Edo period": (("Edo period", "Edo-period"), "The two and a half centuries of the shogunate's rule, 1603-1868, from which most of the record's Japanese evidence comes."),
    "azemichi": (("azemichi",), "A walking bund: the wider paddy bund, two to five feet across, that carries a path, as against the ordinary foot-wide dividing bund."),
    "kochi seiri": (("kochi seiri", "kochi-seiri"), "Land consolidation: the Meiji-era program that regularized paddies into rectangles on true north-south lines, each on a road and a channel - the tidy grid a pre-modern map must not show."),
    "tanada": (("tanada",), "Terraced paddies: flights of small bunded basins stepped down a hillside, each held by a retaining riser."),
    "seijoue": (("seijoue",), "Row planting: setting rice seedlings in straight lines both ways with ropes or a frame - rare before the 1890s, so a pre-modern paddy is planted in a scatter."),
    "nakaboshi": (("nakaboshi",), "The mid-season drain: about a month after transplanting the paddy is emptied and dried until the surface cracks, then flooded again."),
    "tillering": (("tillering",), "The stage after rooting when a rice plant throws up side shoots; shallow warm water encourages it."),
    "renge": (("renge",), "Chinese milk vetch: a legume grown in the drained paddy over winter and plowed under before the spring flooding as green manure."),
    "azolla": (("azolla",), "A floating water fern that lives with nitrogen-fixing algae on the flooded paddy and feeds nitrogen to the rice."),
    "shahi": (("shahi",), "A reservoir's inclined intake on the pond face, drawing the stored water into the conduit (sokohi) through the bottom of the dam."),
    "sokohi": (("sokohi",), "The conduit through the bottom of a reservoir's dam, fed by the inclined intake (shahi) on the pond face."),
    "yohaisui bunri": (("yohaisui bunri",), "Separate supply and drainage: a ditch on each side of every paddy, one to fill it and one to empty it - a Meiji land-readjustment feature, not a pre-modern one."),
    "mizugashira": (("mizugashira",), "Water-heads: the villagers elected to run the irrigation flow and its turns."),
    "steading": (("steadings", "steading"), "A farmstead: a farmhouse with its yard and outbuildings."),
    "bu": (("bu",), "A unit of land area the size of a tsubo, about 3.3 square meters; the cadastres give homestead lots in bu."),
    "momi": (("momi",), "Unhulled rice as it comes off the plant, before milling - the harvest that is spread on the yard to dry."),
    "mugi": (("mugi",), "Barley and the other dry-field grains, whose whole crop is spread on the yard to dry, so a barley district's yards run larger than a rice hamlet's."),
    "cadastre": (("cadastres", "cadastre", "cadastral survey"), "The land-survey register a domain kept of every holding, house and plot, from which lot sizes and holdings are tabulated."),
    "lognormal": (("lognormal",), "A right-skewed spread in which most values sit near the median and a long tail runs toward the large - the shape the cadastres show for house and yard sizes."),
    "naya": (("naya",), "A farmstead's barn: the general work-and-storage building beside the house."),
    "koedame": (("koedame",), "The night-soil pit: a buried jar or plastered pit a meter or so across, in which night soil was rotted down for a few weeks before it went on the fields."),
    "kawaya": (("kawaya", "benjo", "setchin"), "The privy: on a farm a single small building apart from the house, its pit the household's manure store."),
    "dosojin": (("dosojin",), "Roadside guardian-deity stones, set most often on the lonely stretches of a highway and near mountain passes."),
    "jizo": (("jizo",), "A roadside stone figure of the bodhisattva who protects travelers and the spirits of dead children, standing at passes and in villages."),
    "kabata": (("kabata",), "A spring-fed household water basin built beside the house, a regional form of Shiga."),
    "tsuijimatsu": (("tsuijimatsu",), "The black pines of an Izumo homestead grove, clipped flat-topped every few years - the one attested topping of grove trees."),
    "fukugi": (("fukugi",), "The evergreen tree Okinawan villages plant in strips around each house against typhoons and the winter monsoon."),
    "keyaki": (("keyaki",), "Zelkova, a tall broadleaf timber tree of the homestead grove's planting list."),
    "hinoki": (("hinoki",), "Japanese cypress, a tall conifer planted for timber beside the cedar."),
    "kuromatsu": (("kuromatsu",), "Japanese black pine, the windbreak pine of coasts and homestead groves."),
    "houlongshan": (("houlongshan",), "The 'back dragon mountain': the wooded hill behind a Chinese village whose grove is kept as its fengshui forest."),
    "shuikou": (("shuikou",), "The water mouth: the fengshui grove at a Chinese village's entrance, where its stream flows out of the village."),
    "basal area": (("basal area",), "The summed cross-section of a stand's trunks per hectare, measured at chest height - a forester's measure of how much wood a stand carries."),
    "stem density": (("stem density",), "The number of tree stems standing on a hectare of wood, of every size."),
    "carr": (("carr",), "A wet woodland of alder and willow on the drying edge of a marsh."),
    "madake": (("madake",), "Japanese timber bamboo, the tall bamboo of basketry, fans and flutes."),
    "moso": (("moso",), "Giant bamboo, the other timber bamboo of Japan, hardy to about -18 C."),
    "culm": (("culms", "culm"), "A bamboo's stem: the hollow, jointed cane, a few inches across on a timber bamboo."),
    "lineage village": (("lineage villages", "lineage village"), "A village of one clan descended from a common ancestor - the settlement form of south China; the great ones hold forests of tens of hectares."),
    "geta": (("geta",), "Japanese wooden clogs: a thong sandal on a wooden sole."),
    "shakuhachi": (("shakuhachi",), "The Japanese end-blown bamboo flute."),
    "guanxiang": (("guanxiang", "guan-xiang"), "The suburb of streets outside a Chinese city gate, along the approach road, where commerce spilled beyond the walls."),
    "mon": (("mon",), "The copper coin of Edo Japan, the smallest unit of cash; as the suffix of a building's name, a gate."),
    "yoriki": (("yoriki",), "A samurai officer serving under a magistrate, over the constables."),
    "rammed earth": (("rammed earth", "hangtu"), "Walling made by pounding damp earth in layers inside a timber form - the oldest form of Chinese city wall, and why those walls run straight."),
    "kegare": (("kegare",), "Death pollution: the ritual defilement of death and blood that Japanese practice kept out of the settlement - why executions, tanning and burial stand downwind, downstream and past the boundary stone."),
    "ofuregaki": (("ofuregaki",), "The shogunate's circulars, passed down to the villages, copied by the headman and posted on the notice board."),
    "shukuba": (("shukuba", "shuku"), "A post town on a highway, with its transport office, inns and relay horses strung along one street."),
    "kawata": (("kawata",), "The Edo-period name for the outcast tanners' community, who held the rights to fallen animals over a territory and did the leather work."),
    "kusaba": (("kusaba", "danna-ba"), "The service territory over which an outcast community held the right to fallen animals."),
    "shironameshi": (("shironameshi",), "Japanese 'white tanning': hides soaked in the river for several days, the hair knifed off, the hide finished with salt and rapeseed oil alone - no lime, tannin, dung or urine."),
    "tatara": (("tatara",), "The traditional Japanese iron furnace: a clay hearth smelting iron sand with charcoal into a bloom of steel and pig iron over several days."),
    "kera": (("kera",), "The raw bloom a tatara produces, crushed and sorted before refining."),
    "zuku": (("zuku",), "Pig iron, the tatara's high-carbon product, refined at a separate forge."),
    "pig iron": (("pig iron",), "The brittle high-carbon iron that runs from a furnace, useless for tools until it is refined."),
    "fining": (("fining",), "Converting pig iron to wrought iron by stirring it semi-molten under a charcoal blast so the carbon burns off - the Chinese chao, 'stir-frying'."),
    "noborigama": (("noborigama", "anagama"), "The climbing kiln: a long chambered kiln built up a slope, firebox at the bottom and chimney at the top, stoked in shifts for days."),
    "kamado": (("kamado",), "A masonry cooking stove; a brewery's rice-steaming hearth."),
    "koji": (("koji",), "The mold culture grown on steamed rice that starts sake, miso and soy fermentation; a brewery keeps a room for it."),
    "sakagura": (("sakagura",), "A sake brewery: vat hall, koji room, steaming hearth, its own well and a rice storehouse behind a shopfront."),
    "kimon": (("kimon",), "The 'demon gate', the northeast: the inauspicious direction pollution was thought to leave by, where a city stacked its outcast quarter, execution ground and pleasure district."),
    "machi": (("machi",), "A commoner ward or block of a Japanese town."),
    "ujiko": (("ujiko",), "A shrine's parishioners: the households of its district, whose subscriptions paid for its gates and festivals."),
    "keidai": (("keidai",), "A shrine's or temple's precinct: the enclosed ground of approach, gate and halls."),
    "sanmai": (("sanmai",), "A village's unsurveyed burial ground on waste land at its edge."),
    "Jodo Shinshu": (("Jodo Shinshu",), "The True Pure Land school of Japanese Buddhism, whose temple priests could marry and pass the temple to a son."),
    "Zhengyi": (("Zhengyi",), "The 'Orthodox Unity' school of Daoism, whose priests marry, live in households and pass ordination down the family."),
    "usufruct": (("usufruct",), "The right to use land and take its produce without owning it."),
    "feng shui": (("feng shui",), "The Chinese practice of siting graves, houses and villages by the lie of hills, water and wind."),
    "Tokugawa": (("Tokugawa",), "The shogunal house that ruled Japan from 1603 to 1868; its era is the Edo period."),
    "Heian": (("Heian",), "The Heian period, 794-1185, when the court at Kyoto ruled Japan."),
    "Tang dynasty": (("Tang dynasty", "Tang-dynasty"), "The Tang, 618-907: the dynasty of the walled, curfewed city ward, and of Chang'an, the capital Nara and Kyoto were modeled on."),
    "Song dynasty": (("Song dynasty", "Song-dynasty"), "The Song, 960-1279: when China's walled wards opened into shop-lined streets, and the dynasty the setting's demographics anchor to."),
    "Ming dynasty": (("Ming dynasty", "Ming-dynasty"), "The Ming, 1368-1644, the dynasty of the great brick city walls."),
    "Qing dynasty": (("Qing dynasty", "Qing-dynasty"), "The Qing, 1644-1912, China's last dynasty, whose gazetteers and surveys supply many of the record's figures."),
    "teramachi": (("teramachi",), "A castle town's temple quarter: the belt along its outer rim where the lord gathered the temples, their spacious precincts doubling as a line of defense."),
    "sogamae": (("sogamae",), "The total enclosure of a whole castle town by moat and earth mounds, as at Odawara and Osaka."),
    "kido": (("kido",), "A ward gate on a Japanese town street, shut at night to seal one block from the next; every tenement row and lane had its own."),
    "roji": (("roji",), "A back lane between the tenement rows of a town block, closed by its own gate at night."),
    "zhalan": (("zhalan",), "The palings that closed each street of Qing Beijing at night against thieves."),
    "lifang": (("lifang", "fang"), "The walled residential ward of a Tang Chinese city, its gates opened and closed by officials to the morning and evening drums; torn down under the Song."),
    "buke-chi": (("buke-chi", "chonin-chi"), "The samurai ground and the townsman ground of a castle town, assigned as separate districts by law."),
    "josui": (("josui",), "An Edo-period aqueduct: an open earth cut from a river weir or spring to the city's edge, then buried wooden and stone pipes under the streets to cistern-wells the residents bucketed from."),
    "kurayashiki": (("kurayashiki",), "A domain's warehouse-and-residence at the Osaka rice market, where its tax rice was auctioned to brokers."),
    "kashi": (("kashi",), "A Japanese riverbank landing: a public quay, often specialized by cargo, with the warehouses, wholesalers and markets along the top of the bank."),
    "gangi": (("gangi", "matou"), "A stepped landing notched into a faced riverbank, usable at any river level because the boat lies against a different tread."),
    "towpath": (("towpaths", "towpath", "qiandao"), "The path along one bank on which teams hauled boats upstream; it exists because of the boats and goes only where they go."),
    "takasebune": (("takasebune",), "A Japanese river barge, roughly 50-60 ft long, poled and hauled on the shallow rivers."),
    "funairi-bori": (("funairi-bori",), "A boat-entry canal cut into a Japanese city so that barges float in to an internal dock - still water, never a live river."),
    "water gate": (("water gates", "water gate", "shuimen"), "A gate in a city wall opening onto a canal rather than a road, so that barges pass inside the walls."),
    "ote-mon": (("ote-mon", "otemon"), "A castle's front gate, at the head of the ceremonial approach; the rear gate (karamete-mon) is typically opposite it."),
    "karamete-mon": (("karamete-mon", "karamete"), "A castle's rear gate, typically opposite the front gate, from which the garrison sorties onto attackers held at the front."),
    "ote-suji": (("ote-suji",), "The ceremonial approach avenue from a castle town into the castle's front gate, with the offices of state flanking it."),
    "enceinte": (("enceinte",), "The whole fortified area of a castle: every bailey plus its moats, of which the keep is about one percent."),
    "nawabari": (("nawabari",), "The ground plan of a Japanese castle's baileys, laid out to the terrain."),
    "ishigaki": (("ishigaki",), "The dry-stone revetment walls of a Japanese castle, run in straight segments with hard corners."),
    "mamian": (("mamian",), "The 'horse-face' bastion: a rectangular spur projecting from a Chinese city wall, spaced a bowshot apart so that neighbors cover each other's curtain with flanking fire."),
    "wengcheng": (("wengcheng",), "A barbican: a small walled enclosure outside a Chinese city gate whose own gate is set off the line of the main one, so an attacker must turn under fire."),
    "lijin": (("lijin", "chaoguan"), "Chinese customs barriers on the canals and trade routes - a Ming-Qing tariff post and a later Qing transit tax; neither stood at a county seat's gates."),
    "bansho": (("bansho",), "A guard office at a Japanese barrier station or gate, where papers and goods were inspected."),
    "tulou": (("tulou",), "The round or rectangular communal fortress-houses of the Hakka of south China, a clan under one roof."),
    "karo": (("karo",), "A domain lord's senior councillors, who decided in council and lived nearest the castle."),
    "Hyōjōsho": (("Hyōjōsho", "Hyojosho"), "The shogunate's supreme judicial council, which sat outside Edo castle."),
    "Roju": (("Roju", "rōjū"), "The shogunate's governing council of senior lords."),
    "neige": (("neige",), "The Grand Secretariat: the Chinese emperor's council of state, inside the palace precinct."),
    "monzen": (("monzen",), "'Before the gate': the neighborhood of shops and inns on the approach to a great temple or shrine."),
    "sando": (("sando",), "A temple's or shrine's approach avenue, from the road to the hall, under its gates."),
    "bodaiji": (("bodaiji", "ujidera"), "A family's own mortuary and patron temple, where its graves and memorial rites are kept."),
    "louzeyuan": (("louzeyuan",), "The public pauper cemetery every Song prefecture and county was ordered to keep from 1104, on high, open, barren ground."),
    "muenzuka": (("muenzuka", "muenbotoke"), "The pauper's mound for the unclaimed dead, and the unclaimed dead themselves."),
    "kasoba": (("kasoba",), "A cremation ground - in Edo a walled hearth inside a temple precinct."),
    "shubiki": (("shubiki",), "The 'red line' on the map that marked Edo's official city limit."),
    "goulan": (("goulan", "wazi"), "The permanent roofed theaters of Song Kaifeng and the pleasure precincts around them."),
    "sento": (("sento", "sentō"), "A public bathhouse: an ordinary shophouse with a fuel yard behind it, one for every two thousand or so residents of Edo."),
    "hirokoji": (("hirokoji",), "A broad avenue cut through Edo as a firebreak after the great fires."),
    "hiyokechi": (("hiyokechi",), "The fire-prevention open lots the shogunate cut into Edo after the fire of 1657."),
    "siheyuan": (("siheyuan",), "The Chinese courtyard house: rooms on four sides of a walled court, its windowless back to the street; the servants in the south row."),
    "yayi": (("yayi",), "A yamen's runners: the constables, messengers and guards who waited in sheds against the inside of its wall."),
    "degawari": (("degawari", "genan", "gejo"), "The rotating fixed-term service on which a samurai household hired its live-in menservants (genan) and maidservants (gejo)."),
    "doshin": (("doshin", "kachi"), "Low-ranking foot samurai and constables, serving under a magistrate's officers and housed with the foot soldiers at the town's edge."),
    "yakata": (("yakata",), "The fortified rural residence of a warrior family of the age of civil wars, before castle towns."),
    "revetment": (("revetments", "revetment"), "A bank faced with stone or timber to hold it against the water."),
    "leat": (("leats", "leat"), "A small engineered channel that feeds or drains a moat or a mill."),
    "quay": (("quays", "quay"), "A faced bank where boats tie up and unload."),
    "jetty": (("jetties", "jetty"), "A landing stage projecting out into the water."),
    "li": (("li",), "A Chinese mile, about 500 meters."),
    "satetsu": (("satetsu",), "Iron sand, Japan's iron ore, smelted with charcoal in a fuel-hungry, low-yield process."),
    "wari-tetsu": (("wari-tetsu",), "The tatara's refined product: flat bars of forgeable iron split from the bloom."),
    "kokubunji": (("kokubunji",), "A provincial temple of the Nara period, in a precinct about 218 m on a side."),
    "bomori": (("bomori",), "The wife of a True Pure Land temple's resident priest, the 'guardian of the temple'."),
    "chenghuangmiao": (("chenghuangmiao", "wenmiao"), "A Chinese county seat's two mandatory temples: the City God temple (chenghuangmiao) and the Confucian school-temple (wenmiao)."),
    "idobata": (("idobata",), "The wellside: the neighborhood's gathering point at a shared well."),
    "kabu-ido": (("kabu-ido",), "Village rules capping the number of wells, kept by the residents to limit quarrels over groundwater."),
    "suiden": (("suiden",), "Wet paddy, as against the dry field (hatake)."),
    "jiegao": (("jiegao",), "A shadoof: a counterweighted lever that lifts a bucket from a well or a channel."),
    "lulu": (("lulu",), "A windlass on a frame over a well, the usual water-lifting gear of north China."),
    "cangue": (("cangue",), "A heavy wooden board locked around an offender's neck, worn in public for months with the crime written on it."),
    "wanghuolou": (("wanghuolou",), "A Song fire-lookout tower with its own standing brigade."),
    "gulou": (("zhonggulou", "gulou", "zhonglou", "qiaolou"), "A Chinese town's drum tower or bell tower (or the two combined), which sounded the gate-opening, the curfew and the night watches; the cheap form is a drum tower over the yamen's own gate."),
    "tsunaba": (("tsunaba",), "The 'rope place': a great rope stretched bank to bank to catch driven logs where a river leaves its gorge."),
    "umagutsu": (("umagutsu",), "Woven straw horse-sandals, worn in place of iron shoes and used up within a day's travel."),
    "sae no kami": (("sae no kami",), "The boundary deity whose stone stands at a village edge, a pass or a crossroads to keep evil and pollution from entering."),
    "weitian": (("weitian", "wei-tian"), "A Chinese polder: low ground by a river, lake or the sea enclosed by a dike that holds the water out, drained and farmed - from the air a chessboard of fields."),
    "dike-pond": (("dike-pond", "dike-ponds", "mulberry-dike fishpond"), "The Pearl delta's farm loop: a pond dug in low ground, its spoil piled into a dike planted with mulberry; the leaves feed silkworms, the silkworm droppings feed the fish, the pond mud goes back onto the dike."),
    "shatian": (("shatian",), "The Pearl delta's outer, silt-built fields, as low and wet as the dike-pond zone but kept in rice."),
    "sericulture": (("sericulture",), "Raising silkworms for silk: rearing them indoors on mulberry leaf, then reeling the cocoons."),
    "pollard": (("pollarded", "pollard", "pollards"), "A tree cut back to the trunk every few years so that it throws a crop of straight shoots; dike willows were pollarded for withies."),
    "withies": (("withies", "withy"), "The pliant willow rods cut from a pollarded tree, used for baskets, hurdles and bank repair."),
    "fascine": (("fascines", "fascine"), "A bundle of brushwood or willow rods laid along a bank to armor it against the wash of the water."),
    "frass": (("frass",), "Silkworm droppings, fed to the fish in the dike-pond loop."),
    "hongo": (("hongo", "edago"), "In Edo Japan the parent village (hongo) and the branch settlement founded from it (edago), whose tax registers stood in the parent's name."),
    "kumigashira": (("kumigashira",), "A village officer under the headman, in charge of a group of households."),
    "murataka": (("murataka",), "A village's assessed yield in koku, the number its tax was set from."),
    "nengu": (("nengu",), "The land tax of Edo Japan, paid mainly in rice."),
    "chinju": (("chinju",), "A settlement's own tutelary shrine, the seat of the deity that guards it."),
    "gazetteer": (("gazetteers", "gazetteer"), "A local history and geography compiled by a Chinese county or province - the record of what a district grew and built."),
    "hojo seibi": (("hojo seibi",), "Japan's postwar consolidation of paddy into uniform machine-sized strips, on a 1963 standard of 30 by 100 meters."),
    "buke-yashiki": (("buke-yashiki",), "A samurai residence compound in a castle town, enclosed by hedge or wall."),
    "tedai": (("tedai",), "The commoner clerks of an intendant's office, hired from the local peasants and townsmen who knew the district."),
    "gundai": (("gundai",), "A senior intendant governing a large tract of the shogunate's land."),
    "oshirasu": (("oshirasu", "shirasu"), "The white-gravel court where a case was heard, the litigants kneeling below the magistrate's raised floor."),
    "neribei": (("neribei", "dobei", "tsuijibei"), "The Japanese earthen walls: plastered earth over a post core (neribei), earth on a stone plinth (dobei), and rammed earth up to a meter thick (tsuijibei); each carries its own small tiled roof."),
    "tensuioke": (("tensuioke",), "A rain-fed fire tub kept at a house's door and on its roof."),
    "iroha-gumi": (("iroha-gumi",), "Edo's town fire brigades, one per district, named after the syllabary."),
    "tsuke-tsubo": (("tsuke-tsubo",), "A year's contract under which a farmer collected a household's night soil in exchange for rice or vegetables."),
    "daidokoro": (("daidokoro",), "The kitchen of a Japanese house, with its clay hearth."),
    "haiden": (("haiden",), "The worship hall of a Shinto shrine, where people pray before the sanctuary."),
    "keiko": (("keiko",), "Daily martial practice; a solo set-form (kata) needs a square of eight to ten feet."),
    "Inari": (("Inari",), "The rice deity, whose small fox-guarded shrine most compounds and villages kept."),

}


def record_glossary_js() -> str:
    """The research record's copy of this glossary, as the JavaScript asset `research/assets/glossary.js`
    (feature 209, GM 2026-09-07: *"apply the same kind of tooltip rules to our research sections that we have
    in our diagram HTML pages"*). ONE glossary serves both surfaces: the map inlines `glossary_for()` into each
    page at write time, and the record's hand-authored pages - static, no build step - load this DERIVED file,
    which `make glossary` writes from the table above and `tests/interactive/test_record_format.py` proves is
    in sync. `record.js` wraps every occurrence of a term in a page's visible text the way `page.js` wraps a
    modal's. Variants longest first, as `glossary_for` orders them, so "head race" wins over "head"."""
    entries = [{"term": term, "variants": sorted(variants, key=len, reverse=True), "def": definition} for term, (variants, definition) in GLOSSARY.items()]
    return (
        "// DERIVED FILE - written by `make glossary` from l7r/diagram/interactive/glossary.py (feature 209). Never edit\n"
        "// here: add or change a term in glossary.py and run `make glossary`; the gate fails while the two differ.\n"
        "window.RECORD_GLOSSARY = " + json.dumps(entries, ensure_ascii=False, indent=1) + ";\n"
    )
